#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

source "${DIR}/../lib/utils.sh"
source "${DIR}/../solidblocks-shell/lib/log.sh"
source "${DIR}/../solidblocks-shell/lib/python.sh"

export VERSION="$(version)"

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

function task_test {
  if [[ "${SKIP_TESTS:-}" == "true" ]]; then
    exit 0
  fi
}


function task_build {
  python_ensure_venv "${DIR}"
  blcks docs ansible --collection "${DIR}/blcks/utils" --target ~/git/solidblocks/doc/content/ansible/utils
}

function task_clean {
  echo ""
}

arg=${1:-}
shift || true
case ${arg} in
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  release-prepare) ;;
  release-artifacts) ;;
  format) ;;
  clean) task_clean "$@" ;;
  *) task_usage ;;
esac