---
name: "cloud1"

providers:
  # use pass password manager for secret storage
  - type: pass
  # ssh keys will be loaded from <name>.key or the default ssh paths
  - type: ssh_key
  # use the Hetzner cloud for needed service resources like VMs, storage, networking, ...
  - type: hcloud

services:
  # spin up a Postgresql database
  - type: postgresql
    name: database1
  # deploy a simple dockerized hello world application using the database as storage backend
  - type: docker
    name: service1
    image: ghcr.io/pellepelster/solidblocks-hello-world:latest
    links:
      - database1
