#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"
DOCKER_OPTIONS="${DOCKER_OPTIONS:-}"

function task_test {

  if [[ "${SKIP_TESTS:-}" =~ .*unit.* ]]; then
    exit 0
  fi

  ${DIR}/../gradlew :solidblocks-ssh:test
}

function task_format() {
  ${DIR}/../gradlew :solidblocks-ssh:spotlessApply
  terraform fmt -recursive
}

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

arg=${1:-}
shift || true
case ${arg} in
  test) task_test "$@" ;;
  format) task_format "$@" ;;
  clean) task_clean "$@" ;;
  release-artifacts) ;;
  release-test);;
  *) task_usage ;;
esac