---
name: cloud1
root_domain: blcks-test.de

providers:
  - type: pass
  - type: ssh_key
    private_key: "test_ed25519.key"
  - type: hcloud

services:
  - type: postgresql
    name: database1
    databases:
      - name: hello-world
  - type: docker
    name: service1
    image: ghcr.io/pellepelster/solidblocks-hello-world:latest
    link:
      - database1
