rootProject.name = "solidblocks"

include(
    "solidblocks-api",
    "solidblocks-core",
    "solidblocks-base",
    "solidblocks-cloud",
    "solidblocks-cli",
    "solidblocks-cloud-init",
    "solidblocks-cloud-model",
    "solidblocks-cloud-provisioner",
    "solidblocks-provisioner",
    "solidblocks-provisioner-consul",
    "solidblocks-provisioner-minio",
    "solidblocks-provisioner-hetzner",
    "solidblocks-provisioner-vault",
    "solidblocks-agent-base",
    "solidblocks-helloworld-agent",
    "solidblocks-vault-agent",
    "solidblocks-service-vault-api",
    "solidblocks-service-vault-backend",
    "solidblocks-ingress-api",
    "solidblocks-ingress-agent",
    "solidblocks-vault",
    "solidblocks-test",
)
