#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

export VERSION="${GITHUB_REF_NAME:-snapshot}"

DOCKER_REGISTRY="ghcr.io"
DOCKER_REPOSITORY="pellepelster"
DOCKER_IMAGE_NAME="solidblocks-hetzner-nuke"
DOCKER_OPTIONS="${DOCKER_OPTIONS:-}"
TEMP_DIR="${DIR}/.test_$$"

function clean_temp_dir {
  rm -rf "${TEMP_DIR}"
}

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

function task_test {
  if [[ -n "${SKIP_TESTS:-}" ]]; then
    exit 0
  fi

  echo "creating temp dir '${TEMP_DIR}'"
  mkdir -p "${TEMP_DIR}"

  trap clean_temp_dir HUP INT QUIT TERM EXIT
  export HCLOUD_TOKEN="${HCLOUD_TOKEN:-$(pass solidblocks/hetzner/hcloud_api_token)}"

  (
    cd "${DIR}/test"
    terraform init -upgrade
    terraform apply -auto-approve
  )

  (
    cd "${TEMP_DIR}"
    unzip "${DIR}/nuker/build/distributions/nuker.zip"
    echo "==================================================================================="
    echo "running simulate"
    echo "==================================================================================="
    ./nuker/bin/nuker simulate
    echo "==================================================================================="
    echo "running nuke"
    echo "==================================================================================="
    ./nuker/bin/nuker nuke
  )
}

function task_build {
  (
    cd "${DIR}"
    ./gradlew assembleDist
    echo "building '${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${VERSION}'"
    docker buildx build --push --platform linux/amd64,linux/arm64 -t "${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${VERSION}" .
  )
}

function task_release_docker {
  echo "<not implemented>"
}

function task_clean {
  echo "<not implemented>"
}

function task_format {
  (
    cd "${DIR}"
    ./gradlew spotlessApply
  )
}

arg=${1:-}
shift || true
case ${arg} in
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  format) task_format "$@" ;;
  clean) task_clean "$@" ;;
  release-docker) task_release_docker "$@" ;;
  *) task_usage ;;
esac