#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

source "${DIR}/../lib/utils.sh"

export VERSION="$(version)"

function task_build {
  ${DIR}/../gradlew :solidblocks-hetzner-dns:assemble
}

function task_test {
  if [[ "${SKIP_TESTS:-}" == "true" ]]; then
    exit 0
  fi

  ${DIR}/../gradlew :solidblocks-hetzner-dns:test
}

function task_clean {
  ${DIR}/../gradlew :solidblocks-hetzner-dns:clean
}

function task_release_artifacts {
  export ORG_GRADLE_PROJECT_signingInMemoryKey="${ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY:-$(pass solidblocks/signing_key)}"
  export ORG_GRADLE_PROJECT_signingInMemoryKeyPassword="${ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD:-$(pass solidblocks/signing_key_password)}"
  export ORG_GRADLE_PROJECT_mavenCentralUsername="${ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME:-$(pass maven/central-portal/user-token/username)}"
  export ORG_GRADLE_PROJECT_mavenCentralPassword="${ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD:-$(pass maven/central-portal/user-token/password)}"
  ${DIR}/../gradlew :solidblocks-hetzner-dns:publishAllPublicationsToMavenCentralRepository
}

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

arg=${1:-}
shift || true
case ${arg} in
  clean) task_clean "$@" ;;
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  test-prepare) ;;
  release-prepare) ;;
  release-artifacts) task_release_artifacts ;;
  release-test) ;;
  *) task_usage ;;
esac