environment:
  - name: GRADLE_OPTS
    description: "default java options"
    value: "-Xmx1024m"
  - name: BUILD_HOST
    valueFrom:
      command: hostname
  - name: BUILD_USER
    valueFrom:
      command: whoami
  - name: VERSION
    description: "version to use for all build artifacts"
    default:
      valueFrom:
        command: [ "git", "rev-parse", "HEAD" ]

tasks:
  - gradle-build:
    description: "build the project"
    shell:
      workdir: "java"
      command: [ "./gradlew", "assemble" ]
  - gradle-test:
    description: "run project unit tests"
    shell:
      workdir: "java"
      command: [ "./gradlew", "check" ]
  - docker-build:
    description: "build docker container"
    dependsOn:
      - build
    docker:
  - terraform-deploy:
    description: "deploy the docker container locally"
    terraform:
      workdir: "terraform"
      command: "apply"
  - python-test:
    description: "run python integration tests"
    python-venv:
      workdir: "python"
      command: [ "pytest" ]
