environment:
  - name: GRADLE_OPTS
    description: "default gradle options"
    value: "-Xmx1024m"
  - name: BUILD_HOST
    valueFrom:
      command: hostname
  - name: BUILD_USER
    valueFrom:
      command: whoami
  - name: VERSION
    description: "version to use for all build artifacts"
    default:
      valueFrom:
        command: [ "git", "rev-parse", "HEAD" ]

tasks:
  - build:
      description: "build the project"
      shell:
        workdir: "backend"
        command: [ "./gradlew", "assemble" ]
  - test:
      description: "run project unit tests"
      shell:
        workdir: "backend"
        command: [ "./gradlew", "check" ]
