#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

DOCKER_IMAGE_NAME="solidblocks-minio"

source "${DIR}/../../solidblocks-shell/software.sh"

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

function task_test {
  software_ensure_terraform
  software_set_export_path
  (
    cd "${DIR}/test/terraform"
    terraform init
    terraform apply --auto-approve
  )
  task_build
  "${DIR}/gradlew" check
}

function task_build {
  (
    cd "${DIR}"
    docker build -t "${DOCKER_IMAGE_NAME}" .
  )
}

function task_clean {
  "${DIR}/gradlew" clean
  rm -rf ${DIR}/test/terraform/.terraform
  rm -rf ${DIR}/test/terraform/*.tfstate
  rm -rf ${DIR}/test/terraform/*.tfstate.backup
  rm -rf ${DIR}/test/terraform/*.lock.hcl
}

arg=${1:-}
shift || true
case ${arg} in
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  clean) task_clean "$@" ;;
  *) task_usage ;;
esac