---
service_name: "{{ environment_name }}-{{ instance_name }}"
pgbackrest_stanza_name: "{{ service_name }}"
pgbackrest_bucket_name: "{{ service_name }}"

backup_s3_uri_style: "host"

extension_pglogical_enabled: false
extension_postgis_enabled: false
extension_pg_ivm_enabled: false
extension_pgvector_enabled: false
extension_pgaudit_enabled: false
