---
service_name: "{{ environment_name }}-{{ instance_name }}"
stanza_name: "{{ service_name }}"

backup_s3_uri_style: "host"

extension_pglogical_enabled: false
extension_postgis_enabled: false
extension_pg_ivm_enabled: false
extension_pgvector_enabled: false
extension_pgaudit_enabled: false

backup_full_schedule: "*-*-* 02:00:00"
backup_incr_schedule: "*-*-* 0/3:00:00"

extra_configuration:
