#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

source "${DIR}/../lib/utils.sh"
export VERSION="$(version)"

TEMP_DIR="${DIR}/.temp_$$"

function clean_temp_dir {
  rm -rf "${TEMP_DIR}"
}

trap clean_temp_dir EXIT

source "${DIR}/../solidblocks-shell/lib/log.sh"
source "${DIR}/../solidblocks-shell/lib/python.sh"

function task_clean() {
    rm -rf ${DIR}/tests/terraform/*.terraform*
    rm -rf ${DIR}/tests/terraform/*.tfstate*
    rm -rf ${DIR}/tests/tofu/.terraform*
    rm -rf ${DIR}/tests/tofu/.tfstate*
}

function task_test() {
  export NON_EXISTING_OVERRIDE="non_existing_override"
  export CUSTOM_ENV_NAME="custom_env_name"
  export OVERRIDE_PASSWORD="override_password"

  task_clean
  poetry run pytest -s $@
}

function task_build() {
    if [[ ! "${VERSION}" =~ "v[0-9]*\.[0-9]*\.[0-9]*" ]]; then
      poetry version "0.0.0-pre"
    else
      poetry version "${VERSION}"
    fi
    poetry install
    poetry build
}

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

arg=${1:-}
shift || true
case ${arg} in
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  format) task_format "$@" ;;
  *) task_usage ;;
esac
