#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

export VERSION="${GITHUB_REF_NAME:-snapshot}"

source "${DIR}/../solidblocks-shell/lib/log.sh"
source "${DIR}/../solidblocks-shell/lib/python.sh"
source "${DIR}/../lib/terraform.sh"

TESTS="x86 arm"

terraform_export_credentials
export TF_VAR_hetzner_dns_api_token="${HETZNER_DNS_API_TOKEN}"

function task_build {
  (
    mkdir -p "${DIR}/build/solidblocks-cloud-init/lib"
    cp -rv ${DIR}/lib/* "${DIR}/build/solidblocks-cloud-init/lib/"

    #mkdir -p "${DIR}/build/solidblocks-cloud-init/bin"
    #cp -rv ${DIR}/bin/* "${DIR}/build/solidblocks-cloud-init/bin/"

    cd "${DIR}/build/solidblocks-cloud-init"

    echo "creating distribution '${DIR}/build/solidblocks-cloud-init-${VERSION}.zip'"
    zip -r "${DIR}/build/solidblocks-cloud-init-${VERSION}.zip" *

    mkdir -p "${DIR}/build/snippets"

    local checksum="$(sha256sum "${DIR}/build/solidblocks-cloud-init-${VERSION}.zip" | cut -f 1 -d " ")"

    sed \
      --expression="s/__SOLIDBLOCKS_VERSION__/${VERSION}/g" \
      --expression="s/__SOLIDBLOCKS_CLOUD_CHECKSUM__/${checksum}/g"  < "${DIR}/templates/snippets/cloud_init_bootstrap_solidblocks.template" > "${DIR}/build/snippets/cloud_init_bootstrap_solidblocks"

    sed "/__BOOTSTRAP_SOLIDBLOCKS_CLOUD__/e cat ${DIR}/build/snippets/cloud_init_bootstrap_solidblocks" "${DIR}/templates/snippets/cloud_init_minimal_skeleton.template" | grep -v "__BOOTSTRAP_SOLIDBLOCKS_CLOUD__" > "${DIR}/build/snippets/cloud_init_minimal_skeleton"
    chmod +x "${DIR}/build/snippets/cloud_init_minimal_skeleton"

    sed "/__BOOTSTRAP_SOLIDBLOCKS_CLOUD__/e cat ${DIR}/build/snippets/cloud_init_bootstrap_solidblocks" "${DIR}/templates/snippets/cloud_init_kitchen_sink.sh.template" | grep -v "__BOOTSTRAP_SOLIDBLOCKS_CLOUD__" > "${DIR}/build/snippets/cloud_init_kitchen_sink.sh"
    chmod +x "${DIR}/build/snippets/cloud_init_kitchen_sink.sh"
  )
}

function task_lint {
  ensure_environment
  find "${DIR}/lib" -name "*.sh" -exec shellcheck {} \;
}

function task_test {
  if [[ "${SKIP_TESTS:-}" == "true" ]]; then
    exit 0
  fi

  for test in ${TESTS}; do
    run_test "${test}"
  done
}

function run_test {
  local test="${1:-}"

  python_ensure_venv "${DIR}"

  terraform_wrapper "${DIR}/test/${test}" apply -auto-approve -var="solidblocks_version=${VERSION}"

  local ssh_config="$(terraform_output "${DIR}/test/${test}" "ssh_config")"

  while ! ssh -F ${ssh_config} "test" test -f /run/cloud-init/result.json; do
    log_echo_error "waiting for '${test}' server cloud init run"
    sleep 1
  done

  SSL_DOMAIN="${test}.blcks.de" "${DIR}/venv/bin/pytest" --ssh-config=${ssh_config} --hosts=test --show-capture=all -s "${DIR}/test/test_${test}.py"

  clean_cloud_resources "${test}"
}


function task_test_ssh {
    local test=${1}
    shift || true
    local ssh_config="$(terraform_output "${DIR}/test/${test}" "ssh_config")"
    ssh -F ${ssh_config} "test" ${@}
}

function clean_cloud_resources() {
  local test=${1}
  shift || true
  terraform_wrapper "${DIR}/test/${test}" destroy -auto-approve -var="solidblocks_version=${VERSION}"
}

function task_clean {
  for test in ${TESTS}; do
    clean_cloud_resources "${test}"
  done

  rm -rf "${DIR}/build"
}

function task_release_docker {
  echo "<not implemented>"
}

function task_format {
  echo "<not implemented>"
}

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

arg=${1:-}
shift || true
case ${arg} in
  lint) task_lint "$@" ;;
  clean) task_clean "$@" ;;
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  format) task_format "$@" ;;
  test-ssh) task_test_ssh "$@" ;;
  release-docker) task_release_docker "$@" ;;
  *) task_usage ;;
esac
