/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package de.solidblocks.api.resources

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ResourceDiffTest {

    @Test
    fun testChanges() {
        assertFalse(ResourceDiff(NullResource).hasChangesOrMissing())
        assertFalse(ResourceDiff(NullResource, changes = emptyList()).hasChangesOrMissing())
        assertFalse(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1"))).hasChangesOrMissing())

        assertTrue(ResourceDiff(NullResource, missing = true).hasChangesOrMissing())
        assertTrue(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1", missing = true))).hasChangesOrMissing())
        assertTrue(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1", changed = true))).hasChangesOrMissing())
    }
}
