/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package de.solidblocks.api.resources

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ResourceDiffTest {

    @Test
    fun testChanges() {
        assertFalse(ResourceDiff(NullResource).needsApply())
        assertFalse(ResourceDiff(NullResource, changes = emptyList()).needsApply())
        assertFalse(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1"))).needsApply())

        assertTrue(ResourceDiff(NullResource, missing = true).needsApply())
        assertTrue(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1", missing = true))).needsApply())
        assertTrue(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1", changed = true))).needsApply())
    }
}
