/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package de.solidblocks.api.resources

import de.solidblocks.core.NullResource
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ResourceDiffTest {

    @Test
    fun testChanges() {
        assertFalse(ResourceDiff(NullResource).hasChanges())
        assertFalse(ResourceDiff(NullResource, changes = emptyList()).hasChanges())
        assertFalse(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1"))).hasChanges())

        assertTrue(ResourceDiff(NullResource, missing = true).hasChanges())
        assertTrue(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1", missing = true))).hasChanges())
        assertTrue(ResourceDiff(NullResource, changes = listOf(ResourceDiffItem("test1", changed = true))).hasChanges())
    }
}
