#!/usr/bin/env bash
set -eux

source /solidblocks/instance/environment
source /solidblocks/lib/configuration.sh
source /solidblocks/lib/config.sh
source /solidblocks/lib/backup.sh
source /solidblocks/lib/storage.sh

for task_metadata in $(find ${NOMAD_TASK_DIR}/../../.. -name "task_metadata.json"); do
	service_id=$(jq -r .serviceId ${task_metadata})
	task_id=$(jq -r .taskId ${task_metadata})

	task_storage_dir="$(storage_task_storage_dir "${service_id}" "${task_id}")"
	backup_full "service_${service_id}_task_${task_id}" "${task_storage_dir}"
done
