#!/usr/bin/env bash
set -eux

source /solidblocks/instance/environment
source /solidblocks/lib/configuration.sh
source /solidblocks/lib/config.sh
source /solidblocks/lib/backup.sh
source /solidblocks/lib/consul.sh

mkdir -p "${CONSUL_BACKUP_DIR}"
CONSUL_HTTP_TOKEN=$(config .consul_master_token) consul snapshot save "${CONSUL_BACKUP_DIR}/consul.snapshot"
