#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

source "${DIR}/../lib/utils.sh"

export VERSION="$(version)"
export TEMP_DIR="${DIR}/.tmp"

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

function s3cmd_wrapper() {
  s3cmd --host-bucket ${S3_HOST} --host ${S3_HOST} --access_key ${S3_KEY_ID} --secret_key ${S3_SECRET_KEY} $@
}

function task_test() {
  if [[ "${SKIP_TESTS:-}" == "true" ]]; then
    exit 0
  fi

  ${DIR}/../gradlew :solidblocks-hetzner-web-s3-docker:check
}


function task_test_run {
  task_test_run_s3
}

function test_ip_address() {
  cat "${DIR}/test/terraform/ipv4_address"
}

function task_test_ssh {
  ssh -F ${DIR}/test/terraform/ssh_config $(test_ip_address) ${@}
}

arg=${1:-}
shift || true
case ${arg} in
  lint) task_lint "$@" ;;
  clean) task_clean "$@" ;;
  build) task_build "$@" ;;
  format) task_format "$@" ;;
  test-provision) task_test_provision "$@" ;;
  test-ssh) task_test_ssh "$@" ;;
  test) task_test "$@" ;;
  release-artifacts) ;;
  release-prepare) task_release_prepare "$@" ;;
  release-test) task_release_test "$@" ;;
  *) task_usage ;;
esac
