---
- name: "copy k3s service file"
  register: k3s_service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: "enable and start k3s service"
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true
