#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

source "${DIR}/../lib/utils.sh"

export VERSION="$(version)"

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

function task_test {
  if [[ "${SKIP_TESTS:-}" =~ .*integration.* ]]; then
    exit 0
  fi

  task_init_testbed
  ${DIR}/../gradlew check
}

function integration_test_blcks_wrapper() {
  if [[ -d "${DIR}/blcks" ]]; then
    "${DIR}/blcks/bin/blcks" $@
  else
    "${DIR}/blcks" $@
  fi
}

function task_init_testbed() {
    export HCLOUD_TOKEN="${HCLOUD_TOKEN:-$(pass solidblocks/hetzner/test/hcloud_api_token)}"

    (
      cd "${DIR}/test/terraform"
      terraform init -upgrade
      terraform apply -auto-approve
    )
}

function task_test_hetzner_asg {
  if [[ "${SKIP_TESTS:-}" =~ .*integration.* ]]; then
    exit 0
  fi

  task_init_testbed

  divider_header " hetzner asg --help"
  integration_test_blcks_wrapper hetzner asg --help
  divider_footer

  divider_header " hetzner asg rotate --help"
  integration_test_blcks_wrapper hetzner asg rotate --help
  divider_footer

  integration_test_blcks_wrapper hetzner asg rotate --loadbalancer application1 --user-data ${DIR}/test/terraform/cloud_init.template --replicas 1
}

function task_test_hetzner_nuke {
  if [[ "${SKIP_TESTS:-}" =~ .*integration.* ]]; then
    exit 0
  fi

  task_init_testbed
  divider_header "--help"
  integration_test_blcks_wrapper --help
  divider_footer

  divider_header "hetzner --help"
  integration_test_blcks_wrapper hetzner --help
  divider_footer

  divider_header "hetzner nuke --help"
  integration_test_blcks_wrapper hetzner nuke --help
  divider_footer

  divider_header "hetzner nuke"
  integration_test_blcks_wrapper hetzner nuke
  divider_footer

  divider_header "hetzner nuke --do-nuke"
  integration_test_blcks_wrapper hetzner nuke --do-nuke
  divider_footer
}

function task_test_terraform {
  if [[ "${SKIP_TESTS:-}" =~ .*integration.* ]]; then
    exit 0
  fi

  export AWS_REGION="eu-central-1"
  export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-$(pass solidblocks/aws/admin/access_key_id)}"
  export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-$(pass solidblocks/aws/admin/secret_access_key)}"

  divider_header "--help"
  integration_test_blcks_wrapper --help
  divider_footer

  divider_header "terraform --help"
  integration_test_blcks_wrapper terraform --help
  divider_footer

  divider_header "tofu --help"
  integration_test_blcks_wrapper tofu --help
  divider_footer

  divider_header "terraform backends --help"
  integration_test_blcks_wrapper terraform backends --help
  divider_footer

  divider_header "tofu backends --help"
  integration_test_blcks_wrapper tofu backends --help
  divider_footer

  divider_header "terraform backends s3 --help"
  integration_test_blcks_wrapper terraform backends s3 --help
  divider_footer

  divider_header "tofu backends s3 --help"
  integration_test_blcks_wrapper tofu backends s3 --help
  divider_footer

  local bucket="test-terraform-$(uuidgen)"

  divider_header "terraform backends s3"
  integration_test_blcks_wrapper terraform backends s3 "${bucket}"
  integration_test_blcks_wrapper terraform backends s3 "${bucket}"
  divider_footer

  divider_header "terraform backends --file /tmp/${bucket}.tf s3"
  integration_test_blcks_wrapper terraform backends s3 --file "/tmp/${bucket}.tf" "${bucket}"
  divider_footer

  bucket="test-tofu-$(uuidgen)"

  divider_header "tofu backends s3"
  integration_test_blcks_wrapper tofu backends s3 "${bucket}"
  divider_footer

  divider_header "tofu backends --file /tmp/${bucket}.tf s3"
  integration_test_blcks_wrapper tofu backends s3 --file "/tmp/${bucket}.tf" "${bucket}"
  divider_footer
}

function task_test_workflow {
  (
    cd ${DIR}/test/no_workflow_file

    divider_header "no_workflow_file -> check"
    integration_test_blcks_wrapper workflow check || true
    divider_footer

    divider_header "no_workflow_file --> --help"
    integration_test_blcks_wrapper workflow --help
    divider_footer
  )

  (
    cd ${DIR}/test/testbed1

    divider_header "testbed1 --> workflow --help"
    "${DIR}/blcks" workflow --help
    divider_footer

    divider_header "testbed1 --> workflow example"
    "${DIR}/blcks" workflow example
    divider_footer

    divider_header "testbed1 --> workflow check"
    "${DIR}/blcks" workflow check
    divider_footer
  )

  (
     cd ${DIR}/test/testbed2

    divider_header "testbed2 --> workflow check"
    "${DIR}/blcks" workflow check || true
    divider_footer
  )
}

function task_test_integration {
  if [[ "${SKIP_TESTS:-}" =~ .*integration.* ]]; then
    exit 0
  fi

  task_test_terraform
  task_test_hetzner_asg
  task_test_hetzner_nuke
}

function divider_header() {
  echo "==================================================================================="
  echo $@
  echo "-----------------------------------------------------------------------------------"
}

function divider_footer() {
  echo "==================================================================================="
  echo ""
  echo ""
}

function task_install_local {
  task_build_linux_amd64
  cp ${DIR}/blcks ~/bin/blcks
}

function task_clean {
  "${DIR}/../gradlew" clean
  rm -rf "${DIR}/blcks"
}

function task_format() {
  ${DIR}/../gradlew :solidblocks-test:spotlessApply
  (
    cd ${DIR}
    terraform fmt -recursive
  )
}

arg=${1:-}
shift || true
case ${arg} in
  install-local) task_install_local "$@" ;;
  test) task_test "$@" ;;
  test-integration) task_test_integration "$@" ;;
  test-hetzner-nuke) task_test_hetzner_nuke "$@" ;;
  test-hetzner-asg) task_test_hetzner_asg "$@" ;;
  test-terraform) task_test_terraform "$@" ;;
  init-testbed) task_init_testbed "$@" ;;
  release-prepare) ;;
  release-artifacts) ;;
  release-test) ;;
  format) task_format ;;
  clean) task_clean "$@" ;;
  *) task_usage ;;
esac