/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxObjects 
 * @param maxSize 
 */


data class ApiBucketQuotas (

    @Json(name = "maxObjects")
    val maxObjects: kotlin.Long? = null,

    @Json(name = "maxSize")
    val maxSize: kotlin.Long? = null

) {


}

