/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param owner 
 * @param read 
 * @param write 
 */


data class ApiBucketKeyPerm (

    @Json(name = "owner")
    val owner: kotlin.Boolean? = null,

    @Json(name = "read")
    val read: kotlin.Boolean? = null,

    @Json(name = "write")
    val write: kotlin.Boolean? = null

) {


}

