/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.GetClusterLayoutResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param layout Details about the new cluster layout
 * @param message Plain-text information about the layout computation (do not try to parse this)
 */


data class ApplyClusterLayoutResponse (

    /* Details about the new cluster layout */
    @Json(name = "layout")
    val layout: GetClusterLayoutResponse,

    /* Plain-text information about the layout computation (do not try to parse this) */
    @Json(name = "message")
    val message: kotlin.collections.List<kotlin.String>

) {


}

