/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param version As a safety measure, the new version number of the layout must be specified here
 */


data class ApplyClusterLayoutRequest (

    /* As a safety measure, the new version number of the layout must be specified here */
    @Json(name = "version")
    val version: kotlin.Long

) {


}

