/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.BlockVersionBacklink

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param garbageCollected 
 * @param refDeleted 
 * @param versionDeleted 
 * @param versionId 
 * @param backlink 
 */


data class BlockVersion (

    @Json(name = "garbageCollected")
    val garbageCollected: kotlin.Boolean,

    @Json(name = "refDeleted")
    val refDeleted: kotlin.Boolean,

    @Json(name = "versionDeleted")
    val versionDeleted: kotlin.Boolean,

    @Json(name = "versionId")
    val versionId: kotlin.String,

    @Json(name = "backlink")
    val backlink: BlockVersionBacklink? = null

) {


}

