/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uploadDeleted 
 * @param uploadGarbageCollected 
 * @param uploadId 
 * @param bucketId 
 * @param key 
 */


data class BlockVersionBacklinkOneOf1Upload (

    @Json(name = "uploadDeleted")
    val uploadDeleted: kotlin.Boolean,

    @Json(name = "uploadGarbageCollected")
    val uploadGarbageCollected: kotlin.Boolean,

    @Json(name = "uploadId")
    val uploadId: kotlin.String,

    @Json(name = "bucketId")
    val bucketId: kotlin.String? = null,

    @Json(name = "key")
    val key: kotlin.String? = null

) {


}

