/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockHash 
 * @param errorCount 
 * @param lastTrySecsAgo 
 * @param nextTryInSecs 
 * @param refcount 
 */


data class BlockError (

    @Json(name = "blockHash")
    val blockHash: kotlin.String,

    @Json(name = "errorCount")
    val errorCount: kotlin.Long,

    @Json(name = "lastTrySecsAgo")
    val lastTrySecsAgo: kotlin.Long,

    @Json(name = "nextTryInSecs")
    val nextTryInSecs: kotlin.Long,

    @Json(name = "refcount")
    val refcount: kotlin.Long

) {


}

