/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.BlockVersionBacklinkOneOf
import fr.deuxfleurs.garagehq.model.BlockVersionBacklinkOneOf1
import fr.deuxfleurs.garagehq.model.BlockVersionBacklinkOneOf1Upload
import fr.deuxfleurs.garagehq.model.BlockVersionBacklinkOneOfObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `object` 
 * @param upload 
 */


data class BlockVersionBacklink (

    @Json(name = "object")
    val `object`: BlockVersionBacklinkOneOfObject,

    @Json(name = "upload")
    val upload: BlockVersionBacklinkOneOf1Upload

) {


}

