/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ApiBucketKeyPerm

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKeyId 
 * @param bucketId 
 * @param permissions 
 */


data class BucketKeyPermChangeRequest (

    @Json(name = "accessKeyId")
    val accessKeyId: kotlin.String,

    @Json(name = "bucketId")
    val bucketId: kotlin.String,

    @Json(name = "permissions")
    val permissions: ApiBucketKeyPerm

) {


}

