/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKeyId 
 * @param alias 
 */


data class BucketLocalAlias (

    @Json(name = "accessKeyId")
    val accessKeyId: kotlin.String,

    @Json(name = "alias")
    val alias: kotlin.String

) {


}

