/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bucketId 
 * @param olderThanSecs 
 */


data class CleanupIncompleteUploadsRequest (

    @Json(name = "bucketId")
    val bucketId: kotlin.String,

    @Json(name = "olderThanSecs")
    val olderThanSecs: kotlin.Long

) {


}

