/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ClusterLayoutVersionStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param gatewayNodes Number of nodes with a gateway role in this layout version
 * @param status Status of this layout version
 * @param storageNodes Number of nodes with an assigned storage capacity in this layout version
 * @param version Version number of this layout version
 */


data class ClusterLayoutVersion (

    /* Number of nodes with a gateway role in this layout version */
    @Json(name = "gatewayNodes")
    val gatewayNodes: kotlin.Long,

    /* Status of this layout version */
    @Json(name = "status")
    val status: ClusterLayoutVersionStatus,

    /* Number of nodes with an assigned storage capacity in this layout version */
    @Json(name = "storageNodes")
    val storageNodes: kotlin.Long,

    /* Version number of this layout version */
    @Json(name = "version")
    val version: kotlin.Long

) {


}

