/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allowMissingData Allow the skip even if a quorum of nodes could not be found for the data among the remaining nodes
 * @param version Version number of the layout to assume is currently up-to-date. This will generally be the current layout version.
 */


data class ClusterLayoutSkipDeadNodesRequest (

    /* Allow the skip even if a quorum of nodes could not be found for the data among the remaining nodes */
    @Json(name = "allowMissingData")
    val allowMissingData: kotlin.Boolean,

    /* Version number of the layout to assume is currently up-to-date. This will generally be the current layout version. */
    @Json(name = "version")
    val version: kotlin.Long

) {


}

