/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ackUpdated Nodes for which the ACK update tracker has been updated to `version`
 * @param syncUpdated If `allow_missing_data` is set, nodes for which the SYNC update tracker has been updated to `version`
 */


data class ClusterLayoutSkipDeadNodesResponse (

    /* Nodes for which the ACK update tracker has been updated to `version` */
    @Json(name = "ackUpdated")
    val ackUpdated: kotlin.collections.List<kotlin.String>,

    /* If `allow_missing_data` is set, nodes for which the SYNC update tracker has been updated to `version` */
    @Json(name = "syncUpdated")
    val syncUpdated: kotlin.collections.List<kotlin.String>

) {


}

