/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param success `true` if Garage managed to connect to this node
 * @param error An error message if Garage did not manage to connect to this node
 */


data class ConnectNodeResponse (

    /* `true` if Garage managed to connect to this node */
    @Json(name = "success")
    val success: kotlin.Boolean,

    /* An error message if Garage did not manage to connect to this node */
    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

