/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ApiBucketKeyPerm

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKeyId 
 * @param alias 
 * @param allow 
 */


data class CreateBucketLocalAlias (

    @Json(name = "accessKeyId")
    val accessKeyId: kotlin.String,

    @Json(name = "alias")
    val alias: kotlin.String,

    @Json(name = "allow")
    val allow: ApiBucketKeyPerm? = null

) {


}

