/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.CreateBucketLocalAlias

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param globalAlias 
 * @param localAlias 
 */


data class CreateBucketRequest (

    @Json(name = "globalAlias")
    val globalAlias: kotlin.String? = null,

    @Json(name = "localAlias")
    val localAlias: CreateBucketLocalAlias? = null

) {


}

