/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param available Number of bytes available
 * @param total Total number of bytes
 */


data class FreeSpaceResp (

    /* Number of bytes available */
    @Json(name = "available")
    val available: kotlin.Long,

    /* Total number of bytes */
    @Json(name = "total")
    val total: kotlin.Long

) {


}

