/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param expired Whether this admin token is expired already
 * @param name Name of the admin API token
 * @param scope Scope of the admin API token, a list of admin endpoint names (such as `GetClusterStatus`, etc), or the special value `*` to allow all admin endpoints
 * @param created Creation date
 * @param expiration Expiration time and date, formatted according to RFC 3339
 * @param id Identifier of the admin token (which is also a prefix of the full bearer token)
 */


data class GetAdminTokenInfoResponse (

    /* Whether this admin token is expired already */
    @Json(name = "expired")
    val expired: kotlin.Boolean,

    /* Name of the admin API token */
    @Json(name = "name")
    val name: kotlin.String,

    /* Scope of the admin API token, a list of admin endpoint names (such as `GetClusterStatus`, etc), or the special value `*` to allow all admin endpoints */
    @Json(name = "scope")
    val scope: kotlin.collections.List<kotlin.String>,

    /* Creation date */
    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    /* Expiration time and date, formatted according to RFC 3339 */
    @Json(name = "expiration")
    val expiration: java.time.OffsetDateTime? = null,

    /* Identifier of the admin token (which is also a prefix of the full bearer token) */
    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

