/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ApiBucketQuotas
import fr.deuxfleurs.garagehq.model.GetBucketInfoKey
import fr.deuxfleurs.garagehq.model.GetBucketInfoWebsiteResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bytes Total number of bytes used by objects in this bucket
 * @param created Bucket creation date
 * @param globalAliases List of global aliases for this bucket
 * @param id Identifier of the bucket
 * @param propertyKeys List of access keys that have permissions granted on this bucket
 * @param objects Number of objects in this bucket
 * @param quotas Quotas that apply to this bucket
 * @param unfinishedMultipartUploadBytes Total number of bytes used by unfinished multipart uploads in this bucket
 * @param unfinishedMultipartUploadParts Number of parts in unfinished multipart uploads in this bucket
 * @param unfinishedMultipartUploads Number of unfinished multipart uploads in this bucket
 * @param unfinishedUploads Number of unfinished uploads in this bucket
 * @param websiteAccess Whether website acces is enabled for this bucket
 * @param websiteConfig Website configuration for this bucket
 */


data class GetBucketInfoResponse (

    /* Total number of bytes used by objects in this bucket */
    @Json(name = "bytes")
    val bytes: kotlin.Long,

    /* Bucket creation date */
    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    /* List of global aliases for this bucket */
    @Json(name = "globalAliases")
    val globalAliases: kotlin.collections.List<kotlin.String>,

    /* Identifier of the bucket */
    @Json(name = "id")
    val id: kotlin.String,

    /* List of access keys that have permissions granted on this bucket */
    @Json(name = "keys")
    val propertyKeys: kotlin.collections.List<GetBucketInfoKey>,

    /* Number of objects in this bucket */
    @Json(name = "objects")
    val objects: kotlin.Long,

    /* Quotas that apply to this bucket */
    @Json(name = "quotas")
    val quotas: ApiBucketQuotas,

    /* Total number of bytes used by unfinished multipart uploads in this bucket */
    @Json(name = "unfinishedMultipartUploadBytes")
    val unfinishedMultipartUploadBytes: kotlin.Long,

    /* Number of parts in unfinished multipart uploads in this bucket */
    @Json(name = "unfinishedMultipartUploadParts")
    val unfinishedMultipartUploadParts: kotlin.Long,

    /* Number of unfinished multipart uploads in this bucket */
    @Json(name = "unfinishedMultipartUploads")
    val unfinishedMultipartUploads: kotlin.Long,

    /* Number of unfinished uploads in this bucket */
    @Json(name = "unfinishedUploads")
    val unfinishedUploads: kotlin.Long,

    /* Whether website acces is enabled for this bucket */
    @Json(name = "websiteAccess")
    val websiteAccess: kotlin.Boolean,

    /* Website configuration for this bucket */
    @Json(name = "websiteConfig")
    val websiteConfig: GetBucketInfoWebsiteResponse? = null

) {


}

