/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ClusterLayoutVersion
import fr.deuxfleurs.garagehq.model.NodeUpdateTrackers

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currentVersion The current version number of the cluster layout
 * @param minAck All nodes in the cluster are aware of layout versions up to this version number (at least)
 * @param versions Layout version history
 * @param updateTrackers Detailed update trackers for nodes (see `https://garagehq.deuxfleurs.fr/blog/2023-12-preserving-read-after-write-consistency/`)
 */


data class GetClusterLayoutHistoryResponse (

    /* The current version number of the cluster layout */
    @Json(name = "currentVersion")
    val currentVersion: kotlin.Long,

    /* All nodes in the cluster are aware of layout versions up to this version number (at least) */
    @Json(name = "minAck")
    val minAck: kotlin.Long,

    /* Layout version history */
    @Json(name = "versions")
    val versions: kotlin.collections.List<ClusterLayoutVersion>,

    /* Detailed update trackers for nodes (see `https://garagehq.deuxfleurs.fr/blog/2023-12-preserving-read-after-write-consistency/`) */
    @Json(name = "updateTrackers")
    val updateTrackers: kotlin.collections.Map<kotlin.String, NodeUpdateTrackers>? = null

) {


}

