/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.LayoutNodeRole
import fr.deuxfleurs.garagehq.model.LayoutParameters
import fr.deuxfleurs.garagehq.model.NodeRoleChange

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param parameters Layout parameters used when the current layout was computed
 * @param partitionSize The size, in bytes, of one Garage partition (= a shard)
 * @param roles List of nodes that currently have a role in the cluster layout
 * @param stagedRoleChanges List of nodes that will have a new role or whose role will be removed in the next version of the cluster layout
 * @param version The current version number of the cluster layout
 * @param stagedParameters Layout parameters to use when computing the next version of the cluster layout
 */


data class GetClusterLayoutResponse (

    /* Layout parameters used when the current layout was computed */
    @Json(name = "parameters")
    val parameters: LayoutParameters,

    /* The size, in bytes, of one Garage partition (= a shard) */
    @Json(name = "partitionSize")
    val partitionSize: kotlin.Long,

    /* List of nodes that currently have a role in the cluster layout */
    @Json(name = "roles")
    val roles: kotlin.collections.List<LayoutNodeRole>,

    /* List of nodes that will have a new role or whose role will be removed in the next version of the cluster layout */
    @Json(name = "stagedRoleChanges")
    val stagedRoleChanges: kotlin.collections.List<NodeRoleChange>,

    /* The current version number of the cluster layout */
    @Json(name = "version")
    val version: kotlin.Long,

    /* Layout parameters to use when computing the next version of the cluster layout */
    @Json(name = "stagedParameters")
    val stagedParameters: LayoutParameters? = null

) {


}

