/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param connectedNodes the nubmer of nodes this Garage node currently has an open connection to
 * @param knownNodes the number of nodes this Garage node has had a TCP connection to since the daemon started
 * @param partitions the total number of partitions of the data (currently always 256)
 * @param partitionsAllOk the number of partitions for which we are connected to all storage nodes responsible of storing it
 * @param partitionsQuorum the number of partitions for which a quorum of write nodes is available
 * @param status One of `healthy`, `degraded` or `unavailable`: - `healthy`: Garage node is connected to all storage nodes - `degraded`: Garage node is not connected to all storage nodes, but a quorum of write nodes is available for all partitions - `unavailable`: a quorum of write nodes is not available for some partitions
 * @param storageNodes the number of storage nodes currently registered in the cluster layout
 * @param storageNodesUp the number of storage nodes to which a connection is currently open
 */


data class GetClusterHealthResponse (

    /* the nubmer of nodes this Garage node currently has an open connection to */
    @Json(name = "connectedNodes")
    val connectedNodes: kotlin.Int,

    /* the number of nodes this Garage node has had a TCP connection to since the daemon started */
    @Json(name = "knownNodes")
    val knownNodes: kotlin.Int,

    /* the total number of partitions of the data (currently always 256) */
    @Json(name = "partitions")
    val partitions: kotlin.Int,

    /* the number of partitions for which we are connected to all storage nodes responsible of storing it */
    @Json(name = "partitionsAllOk")
    val partitionsAllOk: kotlin.Int,

    /* the number of partitions for which a quorum of write nodes is available */
    @Json(name = "partitionsQuorum")
    val partitionsQuorum: kotlin.Int,

    /* One of `healthy`, `degraded` or `unavailable`: - `healthy`: Garage node is connected to all storage nodes - `degraded`: Garage node is not connected to all storage nodes, but a quorum of write nodes is available for all partitions - `unavailable`: a quorum of write nodes is not available for some partitions */
    @Json(name = "status")
    val status: kotlin.String,

    /* the number of storage nodes currently registered in the cluster layout */
    @Json(name = "storageNodes")
    val storageNodes: kotlin.Int,

    /* the number of storage nodes to which a connection is currently open */
    @Json(name = "storageNodesUp")
    val storageNodesUp: kotlin.Int

) {


}

