/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.NodeResp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param layoutVersion Current version number of the cluster layout
 * @param nodes List of nodes that are either currently connected, part of the current cluster layout, or part of an older cluster layout that is still active in the cluster (being drained).
 */


data class GetClusterStatusResponse (

    /* Current version number of the cluster layout */
    @Json(name = "layoutVersion")
    val layoutVersion: kotlin.Long,

    /* List of nodes that are either currently connected, part of the current cluster layout, or part of an older cluster layout that is still active in the cluster (being drained). */
    @Json(name = "nodes")
    val nodes: kotlin.collections.List<NodeResp>

) {


}

