/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.KeyInfoBucketResponse
import fr.deuxfleurs.garagehq.model.KeyPerm

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKeyId 
 * @param buckets 
 * @param expired 
 * @param name 
 * @param permissions 
 * @param created 
 * @param expiration 
 * @param secretAccessKey 
 */


data class GetKeyInfoResponse (

    @Json(name = "accessKeyId")
    val accessKeyId: kotlin.String,

    @Json(name = "buckets")
    val buckets: kotlin.collections.List<KeyInfoBucketResponse>,

    @Json(name = "expired")
    val expired: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "permissions")
    val permissions: KeyPerm,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "expiration")
    val expiration: java.time.OffsetDateTime? = null,

    @Json(name = "secretAccessKey")
    val secretAccessKey: kotlin.String? = null

) {


}

