/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessKeyId 
 * @param secretAccessKey 
 * @param name 
 */


data class ImportKeyRequest (

    @Json(name = "accessKeyId")
    val accessKeyId: kotlin.String,

    @Json(name = "secretAccessKey")
    val secretAccessKey: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

