/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hash Hash (blake2 sum) of the block's data
 * @param offset Offset of this block within the part
 * @param partNumber Part number of the part containing this block, for multipart uploads
 * @param propertySize Length of the blocks's data
 */


data class InspectObjectBlock (

    /* Hash (blake2 sum) of the block's data */
    @Json(name = "hash")
    val hash: kotlin.String,

    /* Offset of this block within the part */
    @Json(name = "offset")
    val offset: kotlin.Long,

    /* Part number of the part containing this block, for multipart uploads */
    @Json(name = "partNumber")
    val partNumber: kotlin.Long,

    /* Length of the blocks's data */
    @Json(name = "size")
    val propertySize: kotlin.Long

) {


}

