/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.InspectObjectBlock

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param aborted Whether this is an aborted upload
 * @param deleteMarker Whether this version is a delete marker (a tombstone indicating that a previous version of the object has been deleted)
 * @param encrypted Whether this object version was created with SSE-C encryption
 * @param `inline` Whether the object's data is stored inline (for small objects)
 * @param timestamp Creation timestamp of this object version
 * @param uploading Whether this object version is still uploading
 * @param uuid Version ID
 * @param blocks List of data blocks for this object version
 * @param etag Etag of this object version
 * @param headers Metadata (HTTP headers) associated with this object version
 * @param propertySize Size of the object, in bytes
 */


data class InspectObjectVersion (

    /* Whether this is an aborted upload */
    @Json(name = "aborted")
    val aborted: kotlin.Boolean,

    /* Whether this version is a delete marker (a tombstone indicating that a previous version of the object has been deleted) */
    @Json(name = "deleteMarker")
    val deleteMarker: kotlin.Boolean,

    /* Whether this object version was created with SSE-C encryption */
    @Json(name = "encrypted")
    val encrypted: kotlin.Boolean,

    /* Whether the object's data is stored inline (for small objects) */
    @Json(name = "inline")
    val `inline`: kotlin.Boolean,

    /* Creation timestamp of this object version */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* Whether this object version is still uploading */
    @Json(name = "uploading")
    val uploading: kotlin.Boolean,

    /* Version ID */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* List of data blocks for this object version */
    @Json(name = "blocks")
    val blocks: kotlin.collections.List<InspectObjectBlock>? = null,

    /* Etag of this object version */
    @Json(name = "etag")
    val etag: kotlin.String? = null,

    /* Metadata (HTTP headers) associated with this object version */
    @Json(name = "headers")
    val headers: kotlin.collections.List<kotlin.collections.List<kotlin.Any>>? = null,

    /* Size of the object, in bytes */
    @Json(name = "size")
    val propertySize: kotlin.Long? = null

) {


}

