/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.InspectObjectVersion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bucketId ID of the bucket containing the inspected object
 * @param key Key of the inspected object
 * @param versions List of versions currently stored for this object
 */


data class InspectObjectResponse (

    /* ID of the bucket containing the inspected object */
    @Json(name = "bucketId")
    val bucketId: kotlin.String,

    /* Key of the inspected object */
    @Json(name = "key")
    val key: kotlin.String,

    /* List of versions currently stored for this object */
    @Json(name = "versions")
    val versions: kotlin.collections.List<InspectObjectVersion>

) {


}

