/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Identifier of the node
 * @param tags List of tags assigned by the cluster administrator
 * @param zone Zone name assigned by the cluster administrator
 * @param capacity Capacity (in bytes) assigned by the cluster administrator, absent for gateway nodes
 * @param storedPartitions Number of partitions stored on this node (a result of the layout computation)
 * @param usableCapacity Capacity (in bytes) that is actually usable on this node in the current layout, which is equal to `stored_partitions` × `partition_size`
 */


data class LayoutNodeRole (

    /* Identifier of the node */
    @Json(name = "id")
    val id: kotlin.String,

    /* List of tags assigned by the cluster administrator */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    /* Zone name assigned by the cluster administrator */
    @Json(name = "zone")
    val zone: kotlin.String,

    /* Capacity (in bytes) assigned by the cluster administrator, absent for gateway nodes */
    @Json(name = "capacity")
    val capacity: kotlin.Long? = null,

    /* Number of partitions stored on this node (a result of the layout computation) */
    @Json(name = "storedPartitions")
    val storedPartitions: kotlin.Long? = null,

    /* Capacity (in bytes) that is actually usable on this node in the current layout, which is equal to `stored_partitions` × `partition_size` */
    @Json(name = "usableCapacity")
    val usableCapacity: kotlin.Long? = null

) {


}

