/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ZoneRedundancy

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param zoneRedundancy Minimum number of zones in which a data partition must be replicated
 */


data class LayoutParameters (

    /* Minimum number of zones in which a data partition must be replicated */
    @Json(name = "zoneRedundancy")
    val zoneRedundancy: ZoneRedundancy

) {


}

