/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.BucketLocalAlias

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param created 
 * @param globalAliases 
 * @param id 
 * @param localAliases 
 */


data class ListBucketsResponseItem (

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "globalAliases")
    val globalAliases: kotlin.collections.List<kotlin.String>,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "localAliases")
    val localAliases: kotlin.collections.List<BucketLocalAlias>

) {


}

