/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param expired 
 * @param id 
 * @param name 
 * @param created 
 * @param expiration 
 */


data class ListKeysResponseItem (

    @Json(name = "expired")
    val expired: kotlin.Boolean,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "expiration")
    val expiration: java.time.OffsetDateTime? = null

) {


}

