/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param busyOnly 
 * @param errorOnly 
 */


data class LocalListWorkersRequest (

    @Json(name = "busyOnly")
    val busyOnly: kotlin.Boolean? = null,

    @Json(name = "errorOnly")
    val errorOnly: kotlin.Boolean? = null

) {


}

