/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dbEngine 
 * @param garageVersion 
 * @param nodeId 
 * @param rustVersion 
 * @param garageFeatures 
 */


data class LocalGetNodeInfoResponse (

    @Json(name = "dbEngine")
    val dbEngine: kotlin.String,

    @Json(name = "garageVersion")
    val garageVersion: kotlin.String,

    @Json(name = "nodeId")
    val nodeId: kotlin.String,

    @Json(name = "rustVersion")
    val rustVersion: kotlin.String,

    @Json(name = "garageFeatures")
    val garageFeatures: kotlin.collections.List<kotlin.String>? = null

) {


}

