/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.LocalRetryBlockResyncRequestOneOf
import fr.deuxfleurs.garagehq.model.LocalRetryBlockResyncRequestOneOf1

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param all 
 * @param blockHashes 
 */


data class LocalRetryBlockResyncRequest (

    @Json(name = "all")
    val all: kotlin.Boolean,

    @Json(name = "blockHashes")
    val blockHashes: kotlin.collections.List<kotlin.String>

) {


}

