/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockRefsPurged 
 * @param blocksPurged 
 * @param objectsDeleted 
 * @param uploadsDeleted 
 * @param versionsDeleted 
 */


data class MultiResponseLocalPurgeBlocksResponseSuccessValue (

    @Json(name = "blockRefsPurged")
    val blockRefsPurged: kotlin.Long,

    @Json(name = "blocksPurged")
    val blocksPurged: kotlin.Long,

    @Json(name = "objectsDeleted")
    val objectsDeleted: kotlin.Long,

    @Json(name = "uploadsDeleted")
    val uploadsDeleted: kotlin.Long,

    @Json(name = "versionsDeleted")
    val versionsDeleted: kotlin.Long

) {


}

