/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.WorkerInfoResp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error Map of node id to error message, for nodes that were unable to complete the API call
 * @param success Map of node id to response returned by this node, for nodes that were able to successfully complete the API call
 */


data class MultiResponseLocalGetWorkerInfoResponse (

    /* Map of node id to error message, for nodes that were unable to complete the API call */
    @Json(name = "error")
    val error: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* Map of node id to response returned by this node, for nodes that were able to successfully complete the API call */
    @Json(name = "success")
    val success: kotlin.collections.Map<kotlin.String, WorkerInfoResp>

) {


}

