/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.BlockVersion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blockHash 
 * @param refcount 
 * @param versions 
 */


data class MultiResponseLocalGetBlockInfoResponseSuccessValue (

    @Json(name = "blockHash")
    val blockHash: kotlin.String,

    @Json(name = "refcount")
    val refcount: kotlin.Long,

    @Json(name = "versions")
    val versions: kotlin.collections.List<BlockVersion>

) {


}

