/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param remove Set `remove` to `true` to remove the node from the layout
 */


data class NodeRoleChangeEnumOneOf (

    /* Set `remove` to `true` to remove the node from the layout */
    @Json(name = "remove")
    val remove: kotlin.Boolean

) {


}

