/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.NodeAssignedRole
import fr.deuxfleurs.garagehq.model.NodeRoleChangeEnumOneOf

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param remove Set `remove` to `true` to remove the node from the layout
 * @param tags List of tags assigned by the cluster administrator
 * @param zone Zone name assigned by the cluster administrator
 * @param capacity Capacity (in bytes) assigned by the cluster administrator, absent for gateway nodes
 */


data class NodeRoleChangeEnum (

    /* Set `remove` to `true` to remove the node from the layout */
    @Json(name = "remove")
    val remove: kotlin.Boolean,

    /* List of tags assigned by the cluster administrator */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    /* Zone name assigned by the cluster administrator */
    @Json(name = "zone")
    val zone: kotlin.String,

    /* Capacity (in bytes) assigned by the cluster administrator, absent for gateway nodes */
    @Json(name = "capacity")
    val capacity: kotlin.Long? = null

) {


}

