/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ack 
 * @param sync 
 * @param syncAck 
 */


data class NodeUpdateTrackers (

    @Json(name = "ack")
    val ack: kotlin.Long,

    @Json(name = "sync")
    val sync: kotlin.Long,

    @Json(name = "syncAck")
    val syncAck: kotlin.Long

) {


}

