/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.FreeSpaceResp
import fr.deuxfleurs.garagehq.model.NodeAssignedRole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param draining Whether this node is part of an older layout version and is draining data.
 * @param id Full-length node identifier
 * @param isUp Whether this node is connected in the cluster
 * @param addr Socket address used by other nodes to connect to this node for RPC
 * @param dataPartition Total and available space on the disk partition(s) containing the data directory(ies)
 * @param garageVersion Garage version
 * @param hostname Hostname of the node
 * @param lastSeenSecsAgo For disconnected nodes, the number of seconds since last contact, or `null` if no contact was established since Garage restarted.
 * @param metadataPartition Total and available space on the disk partition containing the metadata directory
 * @param role Role assigned to this node in the current cluster layout
 */


data class NodeResp (

    /* Whether this node is part of an older layout version and is draining data. */
    @Json(name = "draining")
    val draining: kotlin.Boolean,

    /* Full-length node identifier */
    @Json(name = "id")
    val id: kotlin.String,

    /* Whether this node is connected in the cluster */
    @Json(name = "isUp")
    val isUp: kotlin.Boolean,

    /* Socket address used by other nodes to connect to this node for RPC */
    @Json(name = "addr")
    val addr: kotlin.String? = null,

    /* Total and available space on the disk partition(s) containing the data directory(ies) */
    @Json(name = "dataPartition")
    val dataPartition: FreeSpaceResp? = null,

    /* Garage version */
    @Json(name = "garageVersion")
    val garageVersion: kotlin.String? = null,

    /* Hostname of the node */
    @Json(name = "hostname")
    val hostname: kotlin.String? = null,

    /* For disconnected nodes, the number of seconds since last contact, or `null` if no contact was established since Garage restarted. */
    @Json(name = "lastSeenSecsAgo")
    val lastSeenSecsAgo: kotlin.Long? = null,

    /* Total and available space on the disk partition containing the metadata directory */
    @Json(name = "metadataPartition")
    val metadataPartition: FreeSpaceResp? = null,

    /* Role assigned to this node in the current cluster layout */
    @Json(name = "role")
    val role: NodeAssignedRole? = null

) {


}

