/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error Error message indicating that the layout could not be computed with the provided configuration
 */


data class PreviewClusterLayoutChangesResponseOneOf (

    /* Error message indicating that the layout could not be computed with the provided configuration */
    @Json(name = "error")
    val error: kotlin.String

) {


}

