/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.GetClusterLayoutResponse
import fr.deuxfleurs.garagehq.model.PreviewClusterLayoutChangesResponseOneOf
import fr.deuxfleurs.garagehq.model.PreviewClusterLayoutChangesResponseOneOf1

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error Error message indicating that the layout could not be computed with the provided configuration
 * @param message Plain-text information about the layout computation (do not try to parse this)
 * @param newLayout Details about the new cluster layout
 */


data class PreviewClusterLayoutChangesResponse (

    /* Error message indicating that the layout could not be computed with the provided configuration */
    @Json(name = "error")
    val error: kotlin.String,

    /* Plain-text information about the layout computation (do not try to parse this) */
    @Json(name = "message")
    val message: kotlin.collections.List<kotlin.String>,

    /* Details about the new cluster layout */
    @Json(name = "newLayout")
    val newLayout: GetClusterLayoutResponse

) {


}

