/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param globalAlias 
 * @param accessKeyId 
 * @param localAlias 
 * @param bucketId 
 */


data class RemoveBucketAliasRequest (

    @Json(name = "globalAlias")
    val globalAlias: kotlin.String,

    @Json(name = "accessKeyId")
    val accessKeyId: kotlin.String,

    @Json(name = "localAlias")
    val localAlias: kotlin.String,

    @Json(name = "bucketId")
    val bucketId: kotlin.String

) {


}

