/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enabled 
 * @param errorDocument 
 * @param indexDocument 
 */


data class UpdateBucketWebsiteAccess (

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "errorDocument")
    val errorDocument: kotlin.String? = null,

    @Json(name = "indexDocument")
    val indexDocument: kotlin.String? = null

) {


}

