/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.LayoutParameters
import fr.deuxfleurs.garagehq.model.NodeRoleChange

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param parameters New layout computation parameters to use
 * @param roles New node roles to assign or remove in the cluster layout
 */


data class UpdateClusterLayoutRequest (

    /* New layout computation parameters to use */
    @Json(name = "parameters")
    val parameters: LayoutParameters? = null,

    /* New node roles to assign or remove in the cluster layout */
    @Json(name = "roles")
    val roles: kotlin.collections.List<NodeRoleChange>? = null

) {


}

