/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param expiration Expiration time and date, formatted according to RFC 3339
 * @param name Name of the admin API token
 * @param neverExpires Set the admin token to never expire
 * @param scope Scope of the admin API token, a list of admin endpoint names (such as `GetClusterStatus`, etc), or the special value `*` to allow all admin endpoints. **WARNING:** Granting a scope of `CreateAdminToken` or `UpdateAdminToken` trivially allows for privilege escalation, and is thus functionnally equivalent to granting a scope of `*`.
 */


data class UpdateAdminTokenRequestBody (

    /* Expiration time and date, formatted according to RFC 3339 */
    @Json(name = "expiration")
    val expiration: java.time.OffsetDateTime? = null,

    /* Name of the admin API token */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Set the admin token to never expire */
    @Json(name = "neverExpires")
    val neverExpires: kotlin.Boolean? = null,

    /* Scope of the admin API token, a list of admin endpoint names (such as `GetClusterStatus`, etc), or the special value `*` to allow all admin endpoints. **WARNING:** Granting a scope of `CreateAdminToken` or `UpdateAdminToken` trivially allows for privilege escalation, and is thus functionnally equivalent to granting a scope of `*`. */
    @Json(name = "scope")
    val scope: kotlin.collections.List<kotlin.String>? = null

) {


}

