/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.KeyPerm

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allow Permissions to allow for the key
 * @param deny Permissions to deny for the key
 * @param expiration Expiration time and date, formatted according to RFC 3339
 * @param name Name of the API key
 * @param neverExpires Set the access key to never expire
 */


data class UpdateKeyRequestBody (

    /* Permissions to allow for the key */
    @Json(name = "allow")
    val allow: KeyPerm? = null,

    /* Permissions to deny for the key */
    @Json(name = "deny")
    val deny: KeyPerm? = null,

    /* Expiration time and date, formatted according to RFC 3339 */
    @Json(name = "expiration")
    val expiration: java.time.OffsetDateTime? = null,

    /* Name of the API key */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Set the access key to never expire */
    @Json(name = "neverExpires")
    val neverExpires: kotlin.Boolean? = null

) {


}

