/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ApiBucketQuotas
import fr.deuxfleurs.garagehq.model.UpdateBucketWebsiteAccess

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param quotas 
 * @param websiteAccess 
 */


data class UpdateBucketRequestBody (

    @Json(name = "quotas")
    val quotas: ApiBucketQuotas? = null,

    @Json(name = "websiteAccess")
    val websiteAccess: UpdateBucketWebsiteAccess? = null

) {


}

