/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.WorkerLastError
import fr.deuxfleurs.garagehq.model.WorkerStateResp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param consecutiveErrors 
 * @param errors 
 * @param freeform 
 * @param id 
 * @param name 
 * @param state 
 * @param lastError 
 * @param persistentErrors 
 * @param progress 
 * @param queueLength 
 * @param tranquility 
 */


data class WorkerInfoResp (

    @Json(name = "consecutiveErrors")
    val consecutiveErrors: kotlin.Long,

    @Json(name = "errors")
    val errors: kotlin.Long,

    @Json(name = "freeform")
    val freeform: kotlin.collections.List<kotlin.String>,

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "state")
    val state: WorkerStateResp,

    @Json(name = "lastError")
    val lastError: WorkerLastError? = null,

    @Json(name = "persistentErrors")
    val persistentErrors: kotlin.Long? = null,

    @Json(name = "progress")
    val progress: kotlin.String? = null,

    @Json(name = "queueLength")
    val queueLength: kotlin.Long? = null,

    @Json(name = "tranquility")
    val tranquility: kotlin.Int? = null

) {


}

