/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.WorkerStateRespOneOf
import fr.deuxfleurs.garagehq.model.WorkerStateRespOneOfThrottled

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param throttled 
 */


data class WorkerStateResp (

    @Json(name = "throttled")
    val throttled: WorkerStateRespOneOfThrottled

) {


}

