/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.model

import fr.deuxfleurs.garagehq.model.ZoneRedundancyOneOf

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atLeast Partitions must be replicated in at least this number of distinct zones.
 */


data class ZoneRedundancy (

    /* Partitions must be replicated in at least this number of distinct zones. */
    @Json(name = "atLeast")
    val atLeast: kotlin.Int

) {


}

