---
argument_specs:
  main:
    short_description: setup k3s servers
    options:
      k3s_api_endpoint:
        description: global load-balanced address for the k3s api endpoint
        required: true
      cilium_hubble_export_allow_list:
        description: flow filter for Cilium hubble exporter, see https://docs.cilium.io/en/latest/observability/hubble/configuration/export/#configuring-hubble-exporter and https://github.com/cilium/hubble#specifying-raw-flow-filters
        required: false
      k3s_api_endpoint_use_ip:
        description: use the api ip address instead of the hostname from `k3s_api_endpoint`
        required: false
