namespace: blcks

name: utils

version: 0.0.0-snapshot

readme: README.md

authors:
- Christian 'Pelle' Pelster <pelle@pelle.io>


description: Various utility roles

license:
- MIT License

license_file: ''

tags: []

dependencies: {}

repository: https://github.com/pellepelster/solidblocks

documentation: https://pellepelster.github.io/solidblocks/

homepage: https://github.com/pellepelster/solidblocks

issues: https://github.com/pellepelster/solidblocks/issues

build_ignore: []

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null

