---
- name: "deploy cilium chart"
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    chart_version: "{{ cilium_version }}"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    values_files:
      - "/root/cilium.values.yml"
