#!/usr/bin/env bash

set -eu

_DIR="$(cd "$(dirname "$0")" ; pwd -P)"

export VERSION="${GITHUB_REF_NAME:-snapshot}"

source "${_DIR}/../solidblocks-shell/lib/python.sh"

function task_build {
  mkdir "${_DIR}/build" || true
  go build -o "${_DIR}/build/solidblocks-terraform"
}

function task_test_unit {
  echo ""
}


function task_test_integration {
  (
    cd "${_DIR}/test"
    python_ensure_venv
    "${_DIR}/test/venv/bin/pytest" --capture=no "${_DIR}/test"
  )
}

function task_test {
  if [[ -n "${SKIP_TESTS:-}" ]]; then
    exit 0
  fi

  task_test_unit
  task_test_integration
}

function task_clean {
  rm -rf "${_DIR}/build"
}

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

arg=${1:-}
shift || true
case ${arg} in
  clean) task_clean "$@" ;;
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  test-unit) task_test_unit "$@" ;;
  test-integration) task_test_integration "$@" ;;
  *) task_usage ;;
esac