/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fr.deuxfleurs.garagehq.model.GetKeyInfoResponse
import fr.deuxfleurs.garagehq.model.ImportKeyRequest
import fr.deuxfleurs.garagehq.model.ListKeysResponseItem
import fr.deuxfleurs.garagehq.model.UpdateKeyRequestBody

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class AccessKeyApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3903")
        }
    }

    /**
     * POST /v2/CreateKey
     * 
     * Creates a new API access key.
     * @param body 
     * @return GetKeyInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createKey(body: UpdateKeyRequestBody) : GetKeyInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createKeyWithHttpInfo(body = body)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetKeyInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/CreateKey
     * 
     * Creates a new API access key.
     * @param body 
     * @return ApiResponse<GetKeyInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createKeyWithHttpInfo(body: UpdateKeyRequestBody) : ApiResponse<GetKeyInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createKeyRequestConfig(body = body)

        return@withContext request<UpdateKeyRequestBody, GetKeyInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createKey
     *
     * @param body 
     * @return RequestConfig
     */
    fun createKeyRequestConfig(body: UpdateKeyRequestBody) : RequestConfig<UpdateKeyRequestBody> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/CreateKey",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/DeleteKey
     * 
     * Delete a key from the cluster. Its access will be removed from all the buckets. Buckets are not automatically deleted and can be dangling. You should manually delete them before. 
     * @param id Access key ID
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun deleteKey(id: kotlin.String) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = deleteKeyWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/DeleteKey
     * 
     * Delete a key from the cluster. Its access will be removed from all the buckets. Buckets are not automatically deleted and can be dangling. You should manually delete them before. 
     * @param id Access key ID
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun deleteKeyWithHttpInfo(id: kotlin.String) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = deleteKeyRequestConfig(id = id)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteKey
     *
     * @param id Access key ID
     * @return RequestConfig
     */
    fun deleteKeyRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("id", listOf(id.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/DeleteKey",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/GetKeyInfo
     * 
     *  Return information about a specific key like its identifiers, its permissions and buckets on which it has permissions. You can search by specifying the exact key identifier (&#x60;id&#x60;) or by specifying a pattern (&#x60;search&#x60;).  For confidentiality reasons, the secret key is not returned by default: you must pass the &#x60;showSecretKey&#x60; query parameter to get it.     
     * @param id Access key ID (optional)
     * @param search Partial key ID or name to search for (optional)
     * @param showSecretKey Whether to return the secret access key (optional)
     * @return GetKeyInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getKeyInfo(id: kotlin.String? = null, search: kotlin.String? = null, showSecretKey: kotlin.Boolean? = null) : GetKeyInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getKeyInfoWithHttpInfo(id = id, search = search, showSecretKey = showSecretKey)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetKeyInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/GetKeyInfo
     * 
     *  Return information about a specific key like its identifiers, its permissions and buckets on which it has permissions. You can search by specifying the exact key identifier (&#x60;id&#x60;) or by specifying a pattern (&#x60;search&#x60;).  For confidentiality reasons, the secret key is not returned by default: you must pass the &#x60;showSecretKey&#x60; query parameter to get it.     
     * @param id Access key ID (optional)
     * @param search Partial key ID or name to search for (optional)
     * @param showSecretKey Whether to return the secret access key (optional)
     * @return ApiResponse<GetKeyInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getKeyInfoWithHttpInfo(id: kotlin.String?, search: kotlin.String?, showSecretKey: kotlin.Boolean?) : ApiResponse<GetKeyInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getKeyInfoRequestConfig(id = id, search = search, showSecretKey = showSecretKey)

        return@withContext request<Unit, GetKeyInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getKeyInfo
     *
     * @param id Access key ID (optional)
     * @param search Partial key ID or name to search for (optional)
     * @param showSecretKey Whether to return the secret access key (optional)
     * @return RequestConfig
     */
    fun getKeyInfoRequestConfig(id: kotlin.String?, search: kotlin.String?, showSecretKey: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (id != null) {
                    put("id", listOf(id.toString()))
                }
                if (search != null) {
                    put("search", listOf(search.toString()))
                }
                if (showSecretKey != null) {
                    put("showSecretKey", listOf(showSecretKey.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/GetKeyInfo",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/ImportKey
     * 
     *  Imports an existing API key. This feature must only be used for migrations and backup restore.  **Do not use it to generate custom key identifiers or you will break your Garage cluster.**     
     * @param importKeyRequest 
     * @return GetKeyInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun importKey(importKeyRequest: ImportKeyRequest) : GetKeyInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = importKeyWithHttpInfo(importKeyRequest = importKeyRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetKeyInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/ImportKey
     * 
     *  Imports an existing API key. This feature must only be used for migrations and backup restore.  **Do not use it to generate custom key identifiers or you will break your Garage cluster.**     
     * @param importKeyRequest 
     * @return ApiResponse<GetKeyInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun importKeyWithHttpInfo(importKeyRequest: ImportKeyRequest) : ApiResponse<GetKeyInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = importKeyRequestConfig(importKeyRequest = importKeyRequest)

        return@withContext request<ImportKeyRequest, GetKeyInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation importKey
     *
     * @param importKeyRequest 
     * @return RequestConfig
     */
    fun importKeyRequestConfig(importKeyRequest: ImportKeyRequest) : RequestConfig<ImportKeyRequest> {
        val localVariableBody = importKeyRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/ImportKey",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/ListKeys
     * 
     * Returns all API access keys in the cluster.
     * @return kotlin.collections.List<ListKeysResponseItem>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listKeys() : kotlin.collections.List<ListKeysResponseItem> = withContext(Dispatchers.IO) {
        val localVarResponse = listKeysWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ListKeysResponseItem>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/ListKeys
     * 
     * Returns all API access keys in the cluster.
     * @return ApiResponse<kotlin.collections.List<ListKeysResponseItem>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listKeysWithHttpInfo() : ApiResponse<kotlin.collections.List<ListKeysResponseItem>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listKeysRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<ListKeysResponseItem>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listKeys
     *
     * @return RequestConfig
     */
    fun listKeysRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/ListKeys",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/UpdateKey
     * 
     *  Updates information about the specified API access key.  *Note: the secret key is not returned in the response, &#x60;null&#x60; is sent instead.*     
     * @param id Access key ID
     * @param updateKeyRequestBody 
     * @return GetKeyInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateKey(id: kotlin.String, updateKeyRequestBody: UpdateKeyRequestBody) : GetKeyInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = updateKeyWithHttpInfo(id = id, updateKeyRequestBody = updateKeyRequestBody)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetKeyInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/UpdateKey
     * 
     *  Updates information about the specified API access key.  *Note: the secret key is not returned in the response, &#x60;null&#x60; is sent instead.*     
     * @param id Access key ID
     * @param updateKeyRequestBody 
     * @return ApiResponse<GetKeyInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateKeyWithHttpInfo(id: kotlin.String, updateKeyRequestBody: UpdateKeyRequestBody) : ApiResponse<GetKeyInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateKeyRequestConfig(id = id, updateKeyRequestBody = updateKeyRequestBody)

        return@withContext request<UpdateKeyRequestBody, GetKeyInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateKey
     *
     * @param id Access key ID
     * @param updateKeyRequestBody 
     * @return RequestConfig
     */
    fun updateKeyRequestConfig(id: kotlin.String, updateKeyRequestBody: UpdateKeyRequestBody) : RequestConfig<UpdateKeyRequestBody> {
        val localVariableBody = updateKeyRequestBody
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("id", listOf(id.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/UpdateKey",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
