/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fr.deuxfleurs.garagehq.model.CreateAdminTokenResponse
import fr.deuxfleurs.garagehq.model.GetAdminTokenInfoResponse
import fr.deuxfleurs.garagehq.model.UpdateAdminTokenRequestBody

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class AdminAPITokenApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3903")
        }
    }

    /**
     * POST /v2/CreateAdminToken
     * 
     * Creates a new admin API token
     * @param updateAdminTokenRequestBody 
     * @return CreateAdminTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createAdminToken(updateAdminTokenRequestBody: UpdateAdminTokenRequestBody) : CreateAdminTokenResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createAdminTokenWithHttpInfo(updateAdminTokenRequestBody = updateAdminTokenRequestBody)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateAdminTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/CreateAdminToken
     * 
     * Creates a new admin API token
     * @param updateAdminTokenRequestBody 
     * @return ApiResponse<CreateAdminTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createAdminTokenWithHttpInfo(updateAdminTokenRequestBody: UpdateAdminTokenRequestBody) : ApiResponse<CreateAdminTokenResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createAdminTokenRequestConfig(updateAdminTokenRequestBody = updateAdminTokenRequestBody)

        return@withContext request<UpdateAdminTokenRequestBody, CreateAdminTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createAdminToken
     *
     * @param updateAdminTokenRequestBody 
     * @return RequestConfig
     */
    fun createAdminTokenRequestConfig(updateAdminTokenRequestBody: UpdateAdminTokenRequestBody) : RequestConfig<UpdateAdminTokenRequestBody> {
        val localVariableBody = updateAdminTokenRequestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/CreateAdminToken",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/DeleteAdminToken
     * 
     * Delete an admin API token from the cluster, revoking all its permissions.
     * @param id Admin API token ID
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun deleteAdminToken(id: kotlin.String) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = deleteAdminTokenWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/DeleteAdminToken
     * 
     * Delete an admin API token from the cluster, revoking all its permissions.
     * @param id Admin API token ID
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun deleteAdminTokenWithHttpInfo(id: kotlin.String) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = deleteAdminTokenRequestConfig(id = id)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteAdminToken
     *
     * @param id Admin API token ID
     * @return RequestConfig
     */
    fun deleteAdminTokenRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("id", listOf(id.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/DeleteAdminToken",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/GetAdminTokenInfo
     * 
     *  Return information about a specific admin API token. You can search by specifying the exact token identifier (&#x60;id&#x60;) or by specifying a pattern (&#x60;search&#x60;).     
     * @param id Admin API token ID (optional)
     * @param search Partial token ID or name to search for (optional)
     * @return GetAdminTokenInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getAdminTokenInfo(id: kotlin.String? = null, search: kotlin.String? = null) : GetAdminTokenInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getAdminTokenInfoWithHttpInfo(id = id, search = search)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetAdminTokenInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/GetAdminTokenInfo
     * 
     *  Return information about a specific admin API token. You can search by specifying the exact token identifier (&#x60;id&#x60;) or by specifying a pattern (&#x60;search&#x60;).     
     * @param id Admin API token ID (optional)
     * @param search Partial token ID or name to search for (optional)
     * @return ApiResponse<GetAdminTokenInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getAdminTokenInfoWithHttpInfo(id: kotlin.String?, search: kotlin.String?) : ApiResponse<GetAdminTokenInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getAdminTokenInfoRequestConfig(id = id, search = search)

        return@withContext request<Unit, GetAdminTokenInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAdminTokenInfo
     *
     * @param id Admin API token ID (optional)
     * @param search Partial token ID or name to search for (optional)
     * @return RequestConfig
     */
    fun getAdminTokenInfoRequestConfig(id: kotlin.String?, search: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (id != null) {
                    put("id", listOf(id.toString()))
                }
                if (search != null) {
                    put("search", listOf(search.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/GetAdminTokenInfo",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/GetCurrentAdminTokenInfo
     * 
     *  Return information about the calling admin API token.     
     * @return GetAdminTokenInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getCurrentAdminTokenInfo() : GetAdminTokenInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getCurrentAdminTokenInfoWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetAdminTokenInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/GetCurrentAdminTokenInfo
     * 
     *  Return information about the calling admin API token.     
     * @return ApiResponse<GetAdminTokenInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getCurrentAdminTokenInfoWithHttpInfo() : ApiResponse<GetAdminTokenInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getCurrentAdminTokenInfoRequestConfig()

        return@withContext request<Unit, GetAdminTokenInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCurrentAdminTokenInfo
     *
     * @return RequestConfig
     */
    fun getCurrentAdminTokenInfoRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/GetCurrentAdminTokenInfo",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/ListAdminTokens
     * 
     * Returns all admin API tokens in the cluster.
     * @return kotlin.collections.List<GetAdminTokenInfoResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listAdminTokens() : kotlin.collections.List<GetAdminTokenInfoResponse> = withContext(Dispatchers.IO) {
        val localVarResponse = listAdminTokensWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<GetAdminTokenInfoResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/ListAdminTokens
     * 
     * Returns all admin API tokens in the cluster.
     * @return ApiResponse<kotlin.collections.List<GetAdminTokenInfoResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listAdminTokensWithHttpInfo() : ApiResponse<kotlin.collections.List<GetAdminTokenInfoResponse>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listAdminTokensRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<GetAdminTokenInfoResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAdminTokens
     *
     * @return RequestConfig
     */
    fun listAdminTokensRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/ListAdminTokens",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/UpdateAdminToken
     * 
     *  Updates information about the specified admin API token.     
     * @param id Admin API token ID
     * @param updateAdminTokenRequestBody 
     * @return GetAdminTokenInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateAdminToken(id: kotlin.String, updateAdminTokenRequestBody: UpdateAdminTokenRequestBody) : GetAdminTokenInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = updateAdminTokenWithHttpInfo(id = id, updateAdminTokenRequestBody = updateAdminTokenRequestBody)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetAdminTokenInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/UpdateAdminToken
     * 
     *  Updates information about the specified admin API token.     
     * @param id Admin API token ID
     * @param updateAdminTokenRequestBody 
     * @return ApiResponse<GetAdminTokenInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateAdminTokenWithHttpInfo(id: kotlin.String, updateAdminTokenRequestBody: UpdateAdminTokenRequestBody) : ApiResponse<GetAdminTokenInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateAdminTokenRequestConfig(id = id, updateAdminTokenRequestBody = updateAdminTokenRequestBody)

        return@withContext request<UpdateAdminTokenRequestBody, GetAdminTokenInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateAdminToken
     *
     * @param id Admin API token ID
     * @param updateAdminTokenRequestBody 
     * @return RequestConfig
     */
    fun updateAdminTokenRequestConfig(id: kotlin.String, updateAdminTokenRequestBody: UpdateAdminTokenRequestBody) : RequestConfig<UpdateAdminTokenRequestBody> {
        val localVariableBody = updateAdminTokenRequestBody
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("id", listOf(id.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/UpdateAdminToken",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
