/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fr.deuxfleurs.garagehq.model.LocalGetBlockInfoRequest
import fr.deuxfleurs.garagehq.model.LocalRetryBlockResyncRequest
import fr.deuxfleurs.garagehq.model.MultiResponseLocalGetBlockInfoResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalListBlockErrorsResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalPurgeBlocksResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalRetryBlockResyncResponse

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class BlockApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3903")
        }
    }

    /**
     * POST /v2/GetBlockInfo
     * 
     *  Get detailed information about a data block stored on a Garage node, including all object versions and in-progress multipart uploads that contain a reference to this block.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetBlockInfoRequest 
     * @return MultiResponseLocalGetBlockInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getBlockInfo(node: kotlin.String, localGetBlockInfoRequest: LocalGetBlockInfoRequest) : MultiResponseLocalGetBlockInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getBlockInfoWithHttpInfo(node = node, localGetBlockInfoRequest = localGetBlockInfoRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalGetBlockInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/GetBlockInfo
     * 
     *  Get detailed information about a data block stored on a Garage node, including all object versions and in-progress multipart uploads that contain a reference to this block.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetBlockInfoRequest 
     * @return ApiResponse<MultiResponseLocalGetBlockInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getBlockInfoWithHttpInfo(node: kotlin.String, localGetBlockInfoRequest: LocalGetBlockInfoRequest) : ApiResponse<MultiResponseLocalGetBlockInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getBlockInfoRequestConfig(node = node, localGetBlockInfoRequest = localGetBlockInfoRequest)

        return@withContext request<LocalGetBlockInfoRequest, MultiResponseLocalGetBlockInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getBlockInfo
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetBlockInfoRequest 
     * @return RequestConfig
     */
    fun getBlockInfoRequestConfig(node: kotlin.String, localGetBlockInfoRequest: LocalGetBlockInfoRequest) : RequestConfig<LocalGetBlockInfoRequest> {
        val localVariableBody = localGetBlockInfoRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/GetBlockInfo",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/ListBlockErrors
     * 
     *  List data blocks that are currently in an errored state on one or several Garage nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return MultiResponseLocalListBlockErrorsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listBlockErrors(node: kotlin.String) : MultiResponseLocalListBlockErrorsResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listBlockErrorsWithHttpInfo(node = node)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalListBlockErrorsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/ListBlockErrors
     * 
     *  List data blocks that are currently in an errored state on one or several Garage nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return ApiResponse<MultiResponseLocalListBlockErrorsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listBlockErrorsWithHttpInfo(node: kotlin.String) : ApiResponse<MultiResponseLocalListBlockErrorsResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listBlockErrorsRequestConfig(node = node)

        return@withContext request<Unit, MultiResponseLocalListBlockErrorsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listBlockErrors
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return RequestConfig
     */
    fun listBlockErrorsRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/ListBlockErrors",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/PurgeBlocks
     * 
     *  Purge references to one or several missing data blocks.  This will remove all objects and in-progress multipart uploads that contain the specified data block(s). The objects will be permanently deleted from the buckets in which they appear. Use with caution.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param requestBody 
     * @return MultiResponseLocalPurgeBlocksResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun purgeBlocks(node: kotlin.String, requestBody: kotlin.collections.List<kotlin.String>) : MultiResponseLocalPurgeBlocksResponse = withContext(Dispatchers.IO) {
        val localVarResponse = purgeBlocksWithHttpInfo(node = node, requestBody = requestBody)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalPurgeBlocksResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/PurgeBlocks
     * 
     *  Purge references to one or several missing data blocks.  This will remove all objects and in-progress multipart uploads that contain the specified data block(s). The objects will be permanently deleted from the buckets in which they appear. Use with caution.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param requestBody 
     * @return ApiResponse<MultiResponseLocalPurgeBlocksResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun purgeBlocksWithHttpInfo(node: kotlin.String, requestBody: kotlin.collections.List<kotlin.String>) : ApiResponse<MultiResponseLocalPurgeBlocksResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = purgeBlocksRequestConfig(node = node, requestBody = requestBody)

        return@withContext request<kotlin.collections.List<kotlin.String>, MultiResponseLocalPurgeBlocksResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation purgeBlocks
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param requestBody 
     * @return RequestConfig
     */
    fun purgeBlocksRequestConfig(node: kotlin.String, requestBody: kotlin.collections.List<kotlin.String>) : RequestConfig<kotlin.collections.List<kotlin.String>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/PurgeBlocks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/RetryBlockResync
     * 
     *  Instruct Garage node(s) to retry the resynchronization of one or several missing data block(s).     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localRetryBlockResyncRequest 
     * @return MultiResponseLocalRetryBlockResyncResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun retryBlockResync(node: kotlin.String, localRetryBlockResyncRequest: LocalRetryBlockResyncRequest) : MultiResponseLocalRetryBlockResyncResponse = withContext(Dispatchers.IO) {
        val localVarResponse = retryBlockResyncWithHttpInfo(node = node, localRetryBlockResyncRequest = localRetryBlockResyncRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalRetryBlockResyncResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/RetryBlockResync
     * 
     *  Instruct Garage node(s) to retry the resynchronization of one or several missing data block(s).     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localRetryBlockResyncRequest 
     * @return ApiResponse<MultiResponseLocalRetryBlockResyncResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun retryBlockResyncWithHttpInfo(node: kotlin.String, localRetryBlockResyncRequest: LocalRetryBlockResyncRequest) : ApiResponse<MultiResponseLocalRetryBlockResyncResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = retryBlockResyncRequestConfig(node = node, localRetryBlockResyncRequest = localRetryBlockResyncRequest)

        return@withContext request<LocalRetryBlockResyncRequest, MultiResponseLocalRetryBlockResyncResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation retryBlockResync
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localRetryBlockResyncRequest 
     * @return RequestConfig
     */
    fun retryBlockResyncRequestConfig(node: kotlin.String, localRetryBlockResyncRequest: LocalRetryBlockResyncRequest) : RequestConfig<LocalRetryBlockResyncRequest> {
        val localVariableBody = localRetryBlockResyncRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/RetryBlockResync",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
