/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fr.deuxfleurs.garagehq.model.AddBucketAliasRequest
import fr.deuxfleurs.garagehq.model.GetBucketInfoResponse
import fr.deuxfleurs.garagehq.model.RemoveBucketAliasRequest

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class BucketAliasApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3903")
        }
    }

    /**
     * POST /v2/AddBucketAlias
     * 
     * Add an alias for the target bucket.  This can be either a global or a local alias, depending on which fields are specified.
     * @param addBucketAliasRequest 
     * @return GetBucketInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun addBucketAlias(addBucketAliasRequest: AddBucketAliasRequest) : GetBucketInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = addBucketAliasWithHttpInfo(addBucketAliasRequest = addBucketAliasRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetBucketInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/AddBucketAlias
     * 
     * Add an alias for the target bucket.  This can be either a global or a local alias, depending on which fields are specified.
     * @param addBucketAliasRequest 
     * @return ApiResponse<GetBucketInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun addBucketAliasWithHttpInfo(addBucketAliasRequest: AddBucketAliasRequest) : ApiResponse<GetBucketInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = addBucketAliasRequestConfig(addBucketAliasRequest = addBucketAliasRequest)

        return@withContext request<AddBucketAliasRequest, GetBucketInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation addBucketAlias
     *
     * @param addBucketAliasRequest 
     * @return RequestConfig
     */
    fun addBucketAliasRequestConfig(addBucketAliasRequest: AddBucketAliasRequest) : RequestConfig<AddBucketAliasRequest> {
        val localVariableBody = addBucketAliasRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/AddBucketAlias",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/RemoveBucketAlias
     * 
     * Remove an alias for the target bucket.  This can be either a global or a local alias, depending on which fields are specified.
     * @param removeBucketAliasRequest 
     * @return GetBucketInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun removeBucketAlias(removeBucketAliasRequest: RemoveBucketAliasRequest) : GetBucketInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = removeBucketAliasWithHttpInfo(removeBucketAliasRequest = removeBucketAliasRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetBucketInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/RemoveBucketAlias
     * 
     * Remove an alias for the target bucket.  This can be either a global or a local alias, depending on which fields are specified.
     * @param removeBucketAliasRequest 
     * @return ApiResponse<GetBucketInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun removeBucketAliasWithHttpInfo(removeBucketAliasRequest: RemoveBucketAliasRequest) : ApiResponse<GetBucketInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = removeBucketAliasRequestConfig(removeBucketAliasRequest = removeBucketAliasRequest)

        return@withContext request<RemoveBucketAliasRequest, GetBucketInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation removeBucketAlias
     *
     * @param removeBucketAliasRequest 
     * @return RequestConfig
     */
    fun removeBucketAliasRequestConfig(removeBucketAliasRequest: RemoveBucketAliasRequest) : RequestConfig<RemoveBucketAliasRequest> {
        val localVariableBody = removeBucketAliasRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/RemoveBucketAlias",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
