/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fr.deuxfleurs.garagehq.model.LocalLaunchRepairOperationRequest
import fr.deuxfleurs.garagehq.model.MultiResponseLocalCreateMetadataSnapshotResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalGetNodeInfoResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalGetNodeStatisticsResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalLaunchRepairOperationResponse

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class NodeApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3903")
        }
    }

    /**
     * POST /v2/CreateMetadataSnapshot
     * 
     *  Instruct one or several nodes to take a snapshot of their metadata databases.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return MultiResponseLocalCreateMetadataSnapshotResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createMetadataSnapshot(node: kotlin.String) : MultiResponseLocalCreateMetadataSnapshotResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createMetadataSnapshotWithHttpInfo(node = node)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalCreateMetadataSnapshotResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/CreateMetadataSnapshot
     * 
     *  Instruct one or several nodes to take a snapshot of their metadata databases.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return ApiResponse<MultiResponseLocalCreateMetadataSnapshotResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createMetadataSnapshotWithHttpInfo(node: kotlin.String) : ApiResponse<MultiResponseLocalCreateMetadataSnapshotResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createMetadataSnapshotRequestConfig(node = node)

        return@withContext request<Unit, MultiResponseLocalCreateMetadataSnapshotResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createMetadataSnapshot
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return RequestConfig
     */
    fun createMetadataSnapshotRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/CreateMetadataSnapshot",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/GetNodeInfo
     * 
     *  Return information about the Garage daemon running on one or several nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return MultiResponseLocalGetNodeInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getNodeInfo(node: kotlin.String) : MultiResponseLocalGetNodeInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getNodeInfoWithHttpInfo(node = node)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalGetNodeInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/GetNodeInfo
     * 
     *  Return information about the Garage daemon running on one or several nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return ApiResponse<MultiResponseLocalGetNodeInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getNodeInfoWithHttpInfo(node: kotlin.String) : ApiResponse<MultiResponseLocalGetNodeInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getNodeInfoRequestConfig(node = node)

        return@withContext request<Unit, MultiResponseLocalGetNodeInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getNodeInfo
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return RequestConfig
     */
    fun getNodeInfoRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/GetNodeInfo",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v2/GetNodeStatistics
     * 
     *  Fetch statistics for one or several Garage nodes.  *Note: do not try to parse the &#x60;freeform&#x60; field of the response, it is given as a string specifically because its format is not stable.*     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return MultiResponseLocalGetNodeStatisticsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getNodeStatistics(node: kotlin.String) : MultiResponseLocalGetNodeStatisticsResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getNodeStatisticsWithHttpInfo(node = node)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalGetNodeStatisticsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v2/GetNodeStatistics
     * 
     *  Fetch statistics for one or several Garage nodes.  *Note: do not try to parse the &#x60;freeform&#x60; field of the response, it is given as a string specifically because its format is not stable.*     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return ApiResponse<MultiResponseLocalGetNodeStatisticsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getNodeStatisticsWithHttpInfo(node: kotlin.String) : ApiResponse<MultiResponseLocalGetNodeStatisticsResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getNodeStatisticsRequestConfig(node = node)

        return@withContext request<Unit, MultiResponseLocalGetNodeStatisticsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getNodeStatistics
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @return RequestConfig
     */
    fun getNodeStatisticsRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/GetNodeStatistics",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/LaunchRepairOperation
     * 
     *  Launch a repair operation on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localLaunchRepairOperationRequest 
     * @return MultiResponseLocalLaunchRepairOperationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun launchRepairOperation(node: kotlin.String, localLaunchRepairOperationRequest: LocalLaunchRepairOperationRequest) : MultiResponseLocalLaunchRepairOperationResponse = withContext(Dispatchers.IO) {
        val localVarResponse = launchRepairOperationWithHttpInfo(node = node, localLaunchRepairOperationRequest = localLaunchRepairOperationRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalLaunchRepairOperationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/LaunchRepairOperation
     * 
     *  Launch a repair operation on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localLaunchRepairOperationRequest 
     * @return ApiResponse<MultiResponseLocalLaunchRepairOperationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun launchRepairOperationWithHttpInfo(node: kotlin.String, localLaunchRepairOperationRequest: LocalLaunchRepairOperationRequest) : ApiResponse<MultiResponseLocalLaunchRepairOperationResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = launchRepairOperationRequestConfig(node = node, localLaunchRepairOperationRequest = localLaunchRepairOperationRequest)

        return@withContext request<LocalLaunchRepairOperationRequest, MultiResponseLocalLaunchRepairOperationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation launchRepairOperation
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localLaunchRepairOperationRequest 
     * @return RequestConfig
     */
    fun launchRepairOperationRequestConfig(node: kotlin.String, localLaunchRepairOperationRequest: LocalLaunchRepairOperationRequest) : RequestConfig<LocalLaunchRepairOperationRequest> {
        val localVariableBody = localLaunchRepairOperationRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/LaunchRepairOperation",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
