/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.deuxfleurs.garagehq.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import fr.deuxfleurs.garagehq.model.LocalGetWorkerInfoRequest
import fr.deuxfleurs.garagehq.model.LocalGetWorkerVariableRequest
import fr.deuxfleurs.garagehq.model.LocalListWorkersRequest
import fr.deuxfleurs.garagehq.model.LocalSetWorkerVariableRequest
import fr.deuxfleurs.garagehq.model.MultiResponseLocalGetWorkerInfoResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalGetWorkerVariableResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalListWorkersResponse
import fr.deuxfleurs.garagehq.model.MultiResponseLocalSetWorkerVariableResponse

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

open class WorkerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3903")
        }
    }

    /**
     * POST /v2/GetWorkerInfo
     * 
     *  Get information about the specified background worker on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetWorkerInfoRequest 
     * @return MultiResponseLocalGetWorkerInfoResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getWorkerInfo(node: kotlin.String, localGetWorkerInfoRequest: LocalGetWorkerInfoRequest) : MultiResponseLocalGetWorkerInfoResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getWorkerInfoWithHttpInfo(node = node, localGetWorkerInfoRequest = localGetWorkerInfoRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalGetWorkerInfoResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/GetWorkerInfo
     * 
     *  Get information about the specified background worker on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetWorkerInfoRequest 
     * @return ApiResponse<MultiResponseLocalGetWorkerInfoResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getWorkerInfoWithHttpInfo(node: kotlin.String, localGetWorkerInfoRequest: LocalGetWorkerInfoRequest) : ApiResponse<MultiResponseLocalGetWorkerInfoResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getWorkerInfoRequestConfig(node = node, localGetWorkerInfoRequest = localGetWorkerInfoRequest)

        return@withContext request<LocalGetWorkerInfoRequest, MultiResponseLocalGetWorkerInfoResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getWorkerInfo
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetWorkerInfoRequest 
     * @return RequestConfig
     */
    fun getWorkerInfoRequestConfig(node: kotlin.String, localGetWorkerInfoRequest: LocalGetWorkerInfoRequest) : RequestConfig<LocalGetWorkerInfoRequest> {
        val localVariableBody = localGetWorkerInfoRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/GetWorkerInfo",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/GetWorkerVariable
     * 
     *  Fetch values of one or several worker variables, from one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetWorkerVariableRequest 
     * @return MultiResponseLocalGetWorkerVariableResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getWorkerVariable(node: kotlin.String, localGetWorkerVariableRequest: LocalGetWorkerVariableRequest) : MultiResponseLocalGetWorkerVariableResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getWorkerVariableWithHttpInfo(node = node, localGetWorkerVariableRequest = localGetWorkerVariableRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalGetWorkerVariableResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/GetWorkerVariable
     * 
     *  Fetch values of one or several worker variables, from one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetWorkerVariableRequest 
     * @return ApiResponse<MultiResponseLocalGetWorkerVariableResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getWorkerVariableWithHttpInfo(node: kotlin.String, localGetWorkerVariableRequest: LocalGetWorkerVariableRequest) : ApiResponse<MultiResponseLocalGetWorkerVariableResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getWorkerVariableRequestConfig(node = node, localGetWorkerVariableRequest = localGetWorkerVariableRequest)

        return@withContext request<LocalGetWorkerVariableRequest, MultiResponseLocalGetWorkerVariableResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getWorkerVariable
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localGetWorkerVariableRequest 
     * @return RequestConfig
     */
    fun getWorkerVariableRequestConfig(node: kotlin.String, localGetWorkerVariableRequest: LocalGetWorkerVariableRequest) : RequestConfig<LocalGetWorkerVariableRequest> {
        val localVariableBody = localGetWorkerVariableRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/GetWorkerVariable",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/ListWorkers
     * 
     *  List background workers currently running on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localListWorkersRequest 
     * @return MultiResponseLocalListWorkersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listWorkers(node: kotlin.String, localListWorkersRequest: LocalListWorkersRequest) : MultiResponseLocalListWorkersResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listWorkersWithHttpInfo(node = node, localListWorkersRequest = localListWorkersRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalListWorkersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/ListWorkers
     * 
     *  List background workers currently running on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localListWorkersRequest 
     * @return ApiResponse<MultiResponseLocalListWorkersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listWorkersWithHttpInfo(node: kotlin.String, localListWorkersRequest: LocalListWorkersRequest) : ApiResponse<MultiResponseLocalListWorkersResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listWorkersRequestConfig(node = node, localListWorkersRequest = localListWorkersRequest)

        return@withContext request<LocalListWorkersRequest, MultiResponseLocalListWorkersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listWorkers
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localListWorkersRequest 
     * @return RequestConfig
     */
    fun listWorkersRequestConfig(node: kotlin.String, localListWorkersRequest: LocalListWorkersRequest) : RequestConfig<LocalListWorkersRequest> {
        val localVariableBody = localListWorkersRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/ListWorkers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v2/SetWorkerVariable
     * 
     *  Set the value for a worker variable, on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localSetWorkerVariableRequest 
     * @return MultiResponseLocalSetWorkerVariableResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun setWorkerVariable(node: kotlin.String, localSetWorkerVariableRequest: LocalSetWorkerVariableRequest) : MultiResponseLocalSetWorkerVariableResponse = withContext(Dispatchers.IO) {
        val localVarResponse = setWorkerVariableWithHttpInfo(node = node, localSetWorkerVariableRequest = localSetWorkerVariableRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MultiResponseLocalSetWorkerVariableResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v2/SetWorkerVariable
     * 
     *  Set the value for a worker variable, on one or several cluster nodes.     
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localSetWorkerVariableRequest 
     * @return ApiResponse<MultiResponseLocalSetWorkerVariableResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun setWorkerVariableWithHttpInfo(node: kotlin.String, localSetWorkerVariableRequest: LocalSetWorkerVariableRequest) : ApiResponse<MultiResponseLocalSetWorkerVariableResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = setWorkerVariableRequestConfig(node = node, localSetWorkerVariableRequest = localSetWorkerVariableRequest)

        return@withContext request<LocalSetWorkerVariableRequest, MultiResponseLocalSetWorkerVariableResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setWorkerVariable
     *
     * @param node Node ID to query, or &#x60;*&#x60; for all nodes, or &#x60;self&#x60; for the node responding to the request
     * @param localSetWorkerVariableRequest 
     * @return RequestConfig
     */
    fun setWorkerVariableRequestConfig(node: kotlin.String, localSetWorkerVariableRequest: LocalSetWorkerVariableRequest) : RequestConfig<LocalSetWorkerVariableRequest> {
        val localVariableBody = localSetWorkerVariableRequest
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("node", listOf(node.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/SetWorkerVariable",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
