---
storage_data_dir: "/storage/data"

k3s_name:
k3s_environment:
k3s_data_dir: "{{ storage_data_dir }}/k3s"

cilium_version: "1.17.3"
cilium_hubble_export_allow_list: [ ]
cilium_ipam_mode: "kubernetes"

cilium_pod_annotations:
  co.elastic.logs/json.add_error_key: "false"
  co.elastic.logs/keys_under_root: "true"
