#!/usr/bin/env bash

set -eu

DIR="$(cd "$(dirname "$0")" ; pwd -P)"

export VERSION="${GITHUB_REF_NAME:-snapshot}"

DOCKER_REGISTRY="ghcr.io"
DOCKER_REPOSITORY="pellepelster"
DOCKER_IMAGE_NAME="solidblocks-rds-postgresql"
DOCKER_OPTIONS="${DOCKER_OPTIONS:-}"

source "${DIR}/../solidblocks-shell/lib/software.sh"

function task_usage {
  echo "Usage: $0 ..."
  exit 1
}

function task_test {
  if [[ -n "${SKIP_TESTS:-}" ]]; then
    exit 0
  fi

  software_ensure_terraform
  software_set_export_path
  (
    cd "${DIR}/test/terraform"
    terraform init
    terraform apply --auto-approve
  )
  (
    export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-$(pass solidblocks/aws/test/secret_access_key)}"
    export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-$(pass solidblocks/aws/test/access_key)}"

    cd "${DIR}"
    ./gradlew check
  )
}

function task_build {
  (
    cd "${DIR}"
    mkdir -p "${DIR}/build"

    docker buildx build \
      --no-cache \
      --platform linux/arm,linux/amd64,linux/arm64 \
      --push \
        -t "${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${VERSION}-rc" \
      .
  )
}

function task_release_docker {
  docker buildx imagetools create -t "${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${VERSION}" "${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${VERSION}-rc"
}

function task_clean {
  rm -rf "${DIR}/build"
  rm -rf ${DIR}/test/terraform/.terraform
  rm -rf ${DIR}/test/terraform/*.tfstate
  rm -rf ${DIR}/test/terraform/*.tfstate.backup
  rm -rf ${DIR}/test/terraform/*.lock.hcl
}

function task_format {
  (
    cd "${DIR}"
    ./gradlew spotlessApply
  )
}

arg=${1:-}
shift || true
case ${arg} in
  build) task_build "$@" ;;
  test) task_test "$@" ;;
  format) task_format "$@" ;;
  clean) task_clean "$@" ;;
  release-docker) task_release_docker "$@" ;;
  *) task_usage ;;
esac