---
- name: "add helm repository key"
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /etc/apt/trusted.gpg.d/helm.asc
    checksum: sha256:dc6e3f91236491ab4af688c9cec2f5ea826817dc37181e59fc7a35e18800c4ab

- name: "add helm repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/helm.asc] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    state: present
    update_cache: true

- name: "install helm"
  ansible.builtin.package:
    name: helm
    state: present
