FROM debian:10

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update
RUN apt-get \
        -o Dpkg::Options::="--force-confnew" \
        --force-yes \
        -fuy \
        dist-upgrade

RUN apt-get install --no-install-recommends -qq -y ca-certificates zip docker.io jq netcat-openbsd curl unzip xz-utils uuid-runtime