[tasks.clean]
run = "rm -rf build"

[tasks.build]
run = "docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/solidblocks-hello-world:latest ."

[tasks.run]
run = """
docker compose build
docker compose up
"""

[tasks."init:env"]
run="""
docker push ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/solidblocks-hello-world:latest
"""


[tasks.preflight-check]
run = [
    { task = "clean" },
    { task = "format" },
    { task = "build" },
    { task = "test" },
]