package de.solidblocks.cloud.provisioner.secret

import de.solidblocks.cloud.api.InfrastructureResourceLookupProvider

interface GenericSecretLookupProvider : InfrastructureResourceLookupProvider<GenericSecretLookup, GenericSecretRuntime>
