[tasks.clean]
run = "rm -rf build"

[tasks.build]
run = "${ROOT_PROJECT}/gradlew :$(basename $PWD):assemble"

[tasks.format]
run = "${ROOT_PROJECT}/gradlew :$(basename $PWD):spotlessApply"

[tasks.test]
run = "${ROOT_PROJECT}/gradlew :$(basename $PWD):check"

[tasks.preflight-check]
run = [
    { task = "clean" },
    { task = "format" },
    { task = "build" },
    { task = "test" },
]

[tasks."release:prepare"]
usage = """
arg "<version>" env="VERSION"
"""
run = """
#!/usr/bin/env bash
set -eu -o pipefail

echo "setting version: ${usage_version}"
mkdir -p ".tmp"
rg -e '^(.*implementation\\("de\\.solidblocks:hetzner-cloud:)(.*)("\\)).*$' "snippets/solidblocks-hetzner-cloud-example/build.gradle.kts" --replace "\\${1}${usage_version}\\${3}" --passthru --no-filename  --no-line-number --color never > ".tmp/build.gradle.kts"
mv ".tmp/build.gradle.kts" "snippets/solidblocks-hetzner-cloud-example/build.gradle.kts"
rm -rf .tmp
"""

[tasks."release:test"]
dir = "snippets/solidblocks-hetzner-cloud-example"
usage = """
arg "<version>" env="VERSION"
"""
run = """
./gradlew clean build
"""
