---
- name: "populate service facts"
  ansible.builtin.service_facts:

#- name: "debug"
#  ansible.builtin.debug:
#    var: hostvars[primary_node]['ansible_all_ipv4_addresses'] | ipaddr(private_subnet) | first

- name: "setting database facts"
  ansible.builtin.set_fact:
    primary_node_hostvars: "{{ hostvars[primary_node] }}"
    is_primary: "{{ inventory_hostname == primary_node }}"

- name: "primary node not found"
  ansible.builtin.fail:
    msg: "primary node '{{ primary_node }}' not found"
  when: not primary_node_hostvars

- name: "database facts"
  ansible.builtin.debug:
    msg: "is_primary: {{ is_primary }}"

- name: "mount data disk"
  ansible.posix.mount:
    path: "{{ storage_mount }}"
    src: "{{ data_device }}"
    fstype: ext4
    state: mounted

- name: "enforce minimum ansible version"
  ansible.builtin.assert:
    that:
      - ansible_version.full is version('2.14', '>=')
    msg: "minimum ansible-core version required is 2.14"

- name: "update apt"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "upgrade packages"
  ansible.builtin.apt:
    upgrade: full

- name: "install python3-psycopg2"
  ansible.builtin.package:
    name: python3-psycopg2
    state: present

- name: "install python3-netaddr"
  ansible.builtin.package:
    name:  python3-netaddr
    state: present

- name: "add postgres repository key"
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/trusted.gpg.d/apt.postgresql.org.asc
    checksum: sha256:0144068502a1eddd2a0280ede10ef607d1ec592ce819940991203941564e8e76

- name: "add postgres repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: true

- name: "install postgresql"
  ansible.builtin.package:
    name: "postgresql-{{ postgres_version }}"
    state: present

- name: "disable default postgres instance"
  ansible.builtin.systemd_service:
    name: postgresql@{{ postgres_version }}-main.service
    enabled: false
    state: stopped

- name: "create postgres data dir"
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    owner: postgres
    group: postgres

- name: "ensure data dir permissions"
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres

- name: "check postgres data dir needs to be initialized"
  find:
    paths: "{{ data_dir }}"
  register: data_dir_content

- name: "set data dir facts"
  ansible.builtin.set_fact:
    data_dir_empty: "{{ data_dir_content.matched == 0 }}"

- name: "data dir facts"
  ansible.builtin.debug:
    msg: "data_dir_empty: {{ data_dir_empty }}"

- name: "setup pglogical extension"
  ansible.builtin.include_tasks:
    file: extensions/pglogical.yml
  when: extension_pglogical_enabled

- name: "setup pgaudit extension"
  ansible.builtin.include_tasks:
    file: extensions/pgaudit.yml
  when: extension_pgaudit_enabled

- name: "setup pgvector extension"
  ansible.builtin.include_tasks:
    file: extensions/pgvector.yml
  when: extension_pgvector_enabled

- name: "setup postgis extension"
  ansible.builtin.include_tasks:
    file: extensions/postgis.yml
  when: extension_postgis_enabled

- name: "setup pg_ivm extension"
  ansible.builtin.include_tasks:
    file: extensions/pg_ivm.yml
  when: extension_pg_ivm_enabled

- name: "write psql.j2"
  ansible.builtin.template:
    src: psql.j2
    dest: "/usr/local/bin/{{ stanza_name }}-psql"
    mode: '0755'

- name: "write pgbackrest.j2"
  ansible.builtin.template:
    src: pgbackrest.j2
    dest: "/usr/local/bin/{{ stanza_name }}-pgbackrest"
    mode: '0755'

- name: "install postgres systemd unit file"
  ansible.builtin.template:
    src: postgres.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: '0600'

- name: "load postgres systemd unit"
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: "{{ service_name }}"
